### ISSUE TITLE
No "full" pooling convention support with MKL-DNN

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#10092]
I'm kind of lacking context here, but I'd like to track this issue. More details are available at https://github.com/apache/incubator-mxnet/pull/10021

@ashokei would you mind summarizing the problem?

**Comment by ashokei** [comment]
@marcoabreu The issue is with a specific SSD-VGG16-reduced model, in which pooling convention of full (only with maxpool) causes failure. 

The solution in #10021 is to fall-back to CPU maxpool/full-pooling convention.  This fallback approach is used anytime we have a config/option not supported by mkl-dnn integration yet. So this is not a "bug" per se. It would be feature that may be enabled / implemented in future. I would remove "bug" as it is misleading for this ticket. With the fix in @10021 this issue will be resolved.

**Comment by marcoabreu** [comment]
Thanks a lot for the explanation. 

Does it fail because it has not been implemented by MKLDNN or because the implementation itself fails?

**Comment by ashokei** [comment]
not been implemented by mkldnn for this specific case, hence with fix in #10021 we fallback to CPU just like any other feature/configure that is not currently implemented/supported-by-mkldnn-integration.

**Comment by pengzhao-intel** [comment]
I think the current change is fine and the path can be back when MKL-DNN supports 'full' pooling convention. 
@ashokei could you also share the implementation plan of MKL-DNN to the community?

**Comment by TaoLv** [comment]
Closed via https://github.com/apache/incubator-mxnet/pull/11047
