### ISSUE TITLE
Executor's set_monitor_callback leaks memory in high-level languages.

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#10692]
## Description
Executor's set_monitor_callback leaks memory in high-level languages.

## Environment info (Required)
OSX, pip installed MXNet.

## Minimum reproducible example
```python
import mxnet as mx
count = 0

def mon_callback(*args, **kwargs):
    global count
    count = count + 1

def main():
    while True:
        process_request()[0].wait_to_read()

def process_request():
    x = mx.sym.Variable('x')
    y = mx.sym.FullyConnected(x, num_hidden=1024)
    for i in range(0, 4):
        y = x + 1
    executor = y.bind(mx.cpu(), {'x': mx.nd.zeros((1024, ))})
    executor.set_monitor_callback(mon_callback)
    return executor.forward(is_train=False)

if __name__ == "__main__":
    main()
```

## Comments
*  Looks like the leak is due to this implementation: https://github.com/apache/incubator-mxnet/blob/master/src/executor/graph_executor.cc#L1461 which copies output ndarrays and then passes back raw pointers to them.  This might make sense for native languages, but if the language accessing the callback is python for example it becomes difficult to properly delete this memory.

**Comment by lupesko** [comment]
@KellenSunderland how much memory does it leak? this may be a critical issue.

This is an MXNet backend issue. 
@marcoabreu can you please remove "C++" and apply "Backend"? thanks!

**Comment by yuxihu** [comment]
@KellenSunderland I changed your script a little bit and I did not see memory leak anymore.
```
import ctypes
import mxnet as mx
from mxnet.base import NDArrayHandle
from mxnet.ndarray import NDArray

count = 0

def mon_callback(*args, **kwargs):
    global count
    count = count + 1
    array = ctypes.cast(args[1], NDArrayHandle)
    array = NDArray(array, writable=False)
```

I think it is not the best practice to pass a raw pointer back to higher level language and rely on users to properly free the memory. I tried to free the memory after we execute the callback in [GraphExecutor](https://github.com/apache/incubator-mxnet/pull/14805/files). However, it caused double free error in some cases where we create NDArray using the raw pointer. In this case, the memory is properly freed, as the modified code above. This is actually what we are doing in [Monitor](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/monitor.py#L70) class.

Please let us know if you have further questions. Otherwise, please close the issue. Thanks.

**Comment by KellenSunderland** [comment]
@yuxihu Yes I was also occasionally getting double frees.  Thanks for the modified code, good reference.  Closing the issue.
