### ISSUE TITLE
Build from sources with Cuda 9.0 cudnn 7.1 on Window 10.

### ISSUE THREAD

**Issue by chaoer** [apache/incubator-mxnet#10745]
Hi, everyone,
Has anyone tried to compile mxnet from sources with Cuda 9.0 cudnn 7.1 on Window 10?

I used VS2015, Cuda 9.0, cudnn7.1.

When I use CMake to generate sln file for VS. I noticed that it print that:
`CUDA detected: 9.0
Found cuDNN (include: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include, library: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib)
Added CUDA NVCC flags for: sm_90` 

When I compile the generated vs project, the compiler told me that compute_90 was not  nvcc supported.

I know that the maximum compute_xx should be compute_70. 
But I don'k know why mx-net will "Added CUDA NVCC flags for compute_90". 
 
Anyone know how to fix this?

**Comment by larroy** [comment]
Can you grep around to see what is trying to use "compute_90" obviously that's not supported. Is it in the visual studio build files?

**Comment by chaoer** [comment]
@larroy 
Thanks for your reply.

As I wrote in the question, the CMake logged information that "Added CUDA NVCC flags for: sm_90". This message was raised from "./3rdarty/mshadow/cmake/Cuda.cmake"(Line around 285-289).
`# setting nvcc arch flags`
`mshadow_select_nvcc_arch_flags(NVCC_FLAGS_EXTRA)`
`list(APPEND CUDA_NVCC_FLAGS ${NVCC_FLAGS_EXTRA})`
`message(STATUS "Added CUDA NVCC flags for: ${NVCC_FLAGS_EXTRA_readable}")`

It's ok to build the sln file using CMake. But when I compiled the "mxnet project" in VS, it reported errors:
`Building NVCC (Device) object`
`CMakeFiles/cuda_compile_1.dir/src/common/Release/cuda_compile_1_generated_random_generator.cu.obj`
`3>  nvcc fatal   : Unsupported gpu architecture 'compute_90'`
`3>  CMake Error at cuda_compile_1_generated_random_generator.cu.obj.Release.cmake:222 (message):`
`3>    Error generating`
`3> E:/caffe_test/mxnet_20180430/build/CMakeFiles/cuda_compile_1.dir/src/common/Release/cuda_compile_1_generated_random_generator.cu.obj`
`3>`

Thus, I think there might be **some problems**  in the function:
`mshadow_select_nvcc_arch_flags`
(But I not so familiar with CMake language, so I don't know how to find the problem and fix it)

**Comment by chaoer** [comment]
@larroy @nswamy 
Finally I find an alternative way to skip this problem.

Step1:  using CMake-gui do the normal configure process;
Step2:  find the CUDA option, an select the "CUDA_ARCH_NAME" to "Manual"; then click configuration;
Step3: change the new appear( usually in red in the GUI) to what you want. (for example: sm_70); then click configuration and generate;
Step4: compile the generated sln file using VS IDE.

**Comment by vipandrew** [comment]
Cuda.cmake is used to detect GPU compute capability by calling nvcc command like "**${CUDA_NVCC_EXECUTABLE} --run  ${__cufile}**" , then regular expression is caled in cmake to extract cuda compute capability string: string(REGEX MATCH "(**[1-9].[0-9]**)" __nvcc_out "${__nvcc_out}")

In my computer with cuda9.0, what the command output is：c:\program files\nvidia gpu computing toolkit\cuda\v**9.0**\include\crt\math_functions.h : warning C4819: .......
**6.1**

Here comes the question, __nvcc_out is set to be 9.0 rather than 6.1(which is the right one we want), since 9.0 is wrongly matched, and that's why we saw "sm_90". Now the solution is clear, add "-w" arguments after nvcc command to depress warnings:  ${CUDA_NVCC_EXECUTABLE} --run  ${__cufile} **"-w"** ..., or change the regular expression to **([^a-zA-Z][1-9]\\\\.[0-9])**.

**Comment by chaoer** [comment]
@vipandrew  Thanks for your kindly reply. This will help a lot.

**Comment by larroy** [comment]
@vipandrew @chaoer  good point, can we create a PR for that?
