### ISSUE TITLE
UX for ONNX Documentation is broken

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#11238]
ONNX documentation for [mxnet v1.2](http://mxnet.incubator.apache.org/versions/1.2.0/api/python/contrib/onnx.html#api-reference) has API Reference section populated. But the [docs page from master](http://mxnet.incubator.apache.org/versions/master/api/python/contrib/onnx.html#api-reference) has empty API reference.

Creating this issue to track this.

@aaronmarkham @spidyDev @Roshrini

**Comment by kalyc** [comment]
@sandeep-krishnamurthy Could you add label "Doc", "ONNX" to this issue?

**Comment by aaronmarkham** [comment]
So this is happening elsewhere too. It seems like a lot of the docs moved one folder deeper, and how they are referenced changed as well. Certain things, like jquery, look for an index.html page in each subfolder. Rather than have a contrib/index.html, we seem to have contrib/contrib.html.

Also, all of the script references like the following that are used to generate the API Reference section are off by one folder.:

```
<script type="text/javascript" src='../../_static/js/auto_module_index.js'></script>
```
This should be `../../../` or just reference the full link: https://mxnet.incubator.apache.org/_static/js/auto_module_index.js

I can easily fix this, but I'm concerned why/how it happened in the first place, and that just updating all of the references to this script is just treating a tiny symptom of a larger problem.

FYI, @kpmurali @thomelane

**Comment by aaronmarkham** [comment]
Upon further investigation I think this commit triggered what we're seeing today.
https://github.com/apache/incubator-mxnet/pull/9534/files
@szha @astonzhang - Can you guy clarify what's going on with the name changes and what you think should be done to fix these errors? Why don't we use index.html anymore for each folder? Why no /api/index.html?

**Comment by szha** [comment]
@aaronmarkham I took a brief look at the PR but I’m not sure how it’s related... which part are you referring to?

**Comment by aaronmarkham** [comment]
Certain things, like jquery, look for an index.html page in each subfolder. Rather than have a contrib/index.html, we seem to have contrib/contrib.html. Same thing for ndarray, etc. We used to have an index page, and now we do not. It looks like Sphinx is expecting index pages in each folder too.
Any insight? This commit, deletes the index page: https://github.com/apache/incubator-mxnet/pull/9534/files
This move may have had unintended consequences.

**Comment by szha** [comment]
what are the unintended consequences? the move is to have text api in contrib package instead of having it as a top level package. the text API doc was never released in text/text.md location.

**Comment by aaronmarkham** [comment]
404s, console errors, JavaScript errors.

I could list them out, but the 404s all follow the same pattern. Index was moved to be the name of the API. 
Foldername/index.html --> Foldername/Foldername.html
It isn't just the text API. 


Possibly related: what is page.js used for? This also seems to expect index.html files and it is broken because of the name changes. If it isn't noticed or used for anything then maybe it can be removed.

**Comment by szha** [comment]
I have no idea about this. The convention you mentioned has been around for quite some time so this isn't really new...
