### ISSUE TITLE
CI error: cannot stat 'nosetests_mkl.xml': No such file or directory

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#11363]
```
cp nosetests_mkl.xml nosetests_python3_mkldnn_cpu_mkl.xml
— Shell Script
<1s
[ut-python3-mkldnn-cpu] Running shell script

+ cp nosetests_mkl.xml nosetests_python3_mkldnn_cpu_mkl.xml

cp: cannot stat 'nosetests_mkl.xml': No such file or directory

script returned exit code 1

```
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11360/1/pipeline/737

**Comment by eric-haibin-lin** [comment]
Also in http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11360/4/pipeline/729 
PYTHON2 CPU

**Comment by marcoabreu** [comment]
Hello,
this is caused by the tests failing. Sometimes, we run multiple test suits in sequence. if the first suite fails to run, the following suits are not generated and thus no report is being created. Everything is working as intended. But I agree that this is misleading - I will see whether I can make the message about storing the test result appear as "Skipped" instead of "error".
