### ISSUE TITLE
Flaky test test_gluon.test_export

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#11616]
Failed build:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1148/pipeline
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/master/runs/1148/nodes/822/log/?start=0

Output:
```
======================================================================
ERROR: test_gluon.test_export
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\jenkins_slave\workspace\ut-python-cpu@3\tests\python\unittest\common.py", line 157, in test_new
    orig_test(*args, **kwargs)
  File "C:\jenkins_slave\workspace\ut-python-cpu@3\tests\python\unittest\test_gluon.py", line 787, in test_export
    prefix='resnet', ctx=ctx, pretrained=True)
  File "C:\jenkins_slave\workspace\ut-python-cpu@3\pkg_vc14_cpu\python\mxnet\gluon\model_zoo\vision\resnet.py", line 406, in resnet18_v1
    return get_resnet(1, 18, **kwargs)
  File "C:\jenkins_slave\workspace\ut-python-cpu@3\pkg_vc14_cpu\python\mxnet\gluon\model_zoo\vision\resnet.py", line 390, in get_resnet
    root=root), ctx=ctx)
  File "C:\jenkins_slave\workspace\ut-python-cpu@3\pkg_vc14_cpu\python\mxnet\gluon\model_zoo\model_store.py", line 114, in get_model_file
    os.remove(zip_file_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Windows\\system32\\config\\systemprofile\\.mxnet\\models\\resnet18_v1-a0666292.zip'

-------------------- >> begin captured stdout << ---------------------
Model file is not found. Downloading.
Downloading C:\Windows\system32\config\systemprofile\.mxnet\models\resnet18_v1-a0666292.zip from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/resnet18_v1-a0666292.zip...
--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): apache-mxnet.s3-accelerate.dualstack.amazonaws.com
requests.packages.urllib3.connectionpool: DEBUG: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com:443 "GET /gluon/models/resnet18_v1-a0666292.zip HTTP/1.1" 200 43452554
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=767602412 to reproduce.
--------------------- >> end captured logging << ---------------------

```

**Comment by szha** [comment]
Looks like a CI problem @marcoabreu

**Comment by marcoabreu** [comment]
To me, it looks like a test problem. It seems like we are hardcoding paths, causing problems if multiple runs are triggered in parallel. The same could happen on a user system if they have multiple processes starting up inside the same container or operating system, so we should consider this as an important bug.

Also, why de we write to system32?

**Comment by szha** [comment]
I was treating sandboxing is a CI problem, as I could hardly think of any circumstance in which we'd want tests from one Jenkins executor to interact with tests in another executor on the same host.

**Comment by szha** [comment]
Even if there is such case, I imagine we'd want to manage it explicitly.

**Comment by szha** [comment]
That particular API uses `$HOME/.mxnet` as the default path, so the system path likely comes from `$HOME`. One simple solution to fix such case is to override `$HOME` and let it point to a managed temporary file path.

**Comment by marcoabreu** [comment]
On production systems while running a service, we can't necessarily assume that every single request is handled in a sandbox. On Ubuntu we actually run in a separate container for every single run, but this is not the case. The windows use case seems to be pretty close to reality.

We don't want to interact in between executors, but that's a side effect because we don't make unique paths. Just load the model zoo in two separate processes and this problem will pop up. 

I'd recommend to store the files in a specific non unique directory and check if they exist (and match the hash) before downloading the archive from the internet. If it doesn't exist, download the zip file to a temporary dir. Then put a readwritelock (shared read, unique write) onto the non unique target path and extract the archive file into it. Right now, the code assumes that we have exclusive access - especially the code which tries to delete the archive file which might be used from a different process because it's also non unique (on mobile, otherwise I'd post the code).

**Comment by marcoabreu** [comment]
Thanks for elaborating on the home variable. That makes sense because we run as administrator on windows.

**Comment by szha** [comment]
This situation has nothing to do with a micro service...

**Comment by KellenSunderland** [comment]
I'd agree this is a sandboxing issue in the CI.  We'll take a look at how we can improve this @szha.

**Comment by marcoabreu** [comment]
To clarify: do we expect our users to be able to run multiple instances of MXNet on the same host?

**Comment by larroy** [comment]
Mostly I agree with Marco. You can't assume that writing to a global path is ok, because this prevents to run tests in parallel in different copies of MXNet which should be possible, as developers often have several copies of the same repo to test different things.

So this test should write to a different location by means of a temporary directory.
The fact that is not a good practice that a unit test writes to disk and instead should avoid IO or use a memory buffer is a broader discussion.

**Comment by marcoabreu** [comment]
Just to clarify: The problem here seems to be function-under-test python\mxnet\gluon\model_zoo\model_store.py:get_model_file, thus it's not the test itself causing the problem but rather the actually tested function having trouble with multi tenancy.

**Comment by larroy** [comment]
@marcoabreu clear, I'm working on a fix.

**Comment by szha** [comment]
Many design decisions are based on having a single instance of mxnet in a system. For example, the mxnet processes don't attempt to find and talk to each other to coordinate on memory allocation. You'd need to change more than the download logic and tests to make it work.

**Comment by szha** [comment]
Having this complexity in the code base just to do what containers should have done doesn't seem the right approach to me.

**Comment by larroy** [comment]
@szha I see your point. Assuming that only one process is able to run on a system goes against 30 years of Unix and multi user OS development. I think is a bad assumption to make in general even if it's the optimal case. Containers are tools that shouldn't be required for correctness.

**Comment by marcoabreu** [comment]
Considering the fact that MXNet is not threadsafe and the interface (CAPI) is single threaded (with sticky thread) together with the assumption that you are only allowed to run a single instance of MXNet puts us in a quite difficult position.

**Comment by larroy** [comment]
You can run several instances of mxnet. Can you elaborate?

**Comment by marcoabreu** [comment]
This is the assumption stated above: "Many design decisions are based on having a single instance of mxnet in a system. "

**Comment by szha** [comment]
@marcoabreu and to you, that statement equals "you are only allowed to run a single instance of MXNet"?

**Comment by szha** [comment]
We can also ask whether one test should affect another in any way, and if so, why, and why not managed explicitly.

**Comment by marcoabreu** [comment]
Yes, because everything else is undefined behaviour, right? If we design a system to be used only in a specific way, we don't "guarantee" anything if people use it differently. How else would you Interpret such a design statement?

**Comment by marcoabreu** [comment]
My stand on that would be that our tests should all be completely self contained. What do you rgibk

**Comment by szha** [comment]
OK. Following this logic, we either have inter-process memory management for GPU or our CPU users can't run multi-process CPU inference. What guarantee does CI have BTW?

**Comment by szha** [comment]
Users don't directly deal with CUDA. They interact with CUDA through MXNet. MXNet has internal memory pool to hold previously allocated memory, without information about GPU memory held by other processes. Thus, running multiple processes on the same GPU, for many workloads will likely meet OOM error. You'd know if you tried.

The CPU inference part wasn't really important. I was just joking about "no inter-process memory management for GPU => no overall multi-tenancy guarantee for MXNet => even CPU users can't rely on multi-tenancy".

Since CI guarantees correctness of tests if run sequentially, and we won't find any problem with the test_export test if we indeed run sequentially on a host without other tests running, does it mean that running tests in parallel is breaking the guarantee?

**Comment by marcoabreu** [comment]
I tried, what you described was exactly my observation: you run out of cuda memory if you run MXNet in parallel. I didn't know we had the memory pool, but that certainly explains it. That problem is the reason all our GPU slaves have only one executors. Is there any possibility to tweak or disable that pool?

We're not in state where we can give actual guarantees at all, that's why I had it in quotes :)

No, running the tests in parallel (which is only the case on windows CPU) only reveals the problems we're having if we actually don't run in sequence.

**Comment by marcoabreu** [comment]
But yeah, we are regularly testing MXNet CPU on windows and don't seem to encounter many problems. I also wouldn't know much reason besides io(like this case) because the os automatically takes care of RAM and CPU.

**Comment by szha** [comment]
`export MXNET_GPU_MEM_POOL_RESERVE=100` should effectively disable the pool.

**Comment by larroy** [comment]
This in addition to @szha env variable should fix this issue, can be closed.
