### ISSUE TITLE
NPE in BucketingModule when providedLabel of DataBatch is not set

### ISSUE THREAD

**Issue by milandesai** [apache/incubator-mxnet#11775]
Package: Scala
Mxnet Version: 1.1.0
Java Version: openjdk 1.8.0_131
Maven Version: [unused]
Scala Runtime: 2.12.4

We create a DataBatch without setting the `providedLabel` field. We then call `BucketingModule.forward(...)` with the data batch and get a NullPointerException:
```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at ml.dmlc.mxnet.DataDesc$.ListMap2Descs(IO.scala:252)
	at ml.dmlc.mxnet.module.BucketingModule.forward(BucketingModule.scala:313)
```

This happens because the implicit method `ListMap2Descs` tries to convert `ListMap[String, Shape]` into `IndexedSeq[DataDesc]` but fails because the former is null by default.

**Comment by lupesko** [comment]
Thanks for reporting the issue @milandesai 

To help the community look into it, please provide more information as asked below (usually the new issue template asks to fill all of that in) - providing complete information in the most concise form is the best way to get help. 
- Package used (Python/R/Scala/Julia):
- For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)
- Build info (Required if built from source)
1. Compiler (gcc/clang/mingw/visual studio):
2. MXNet commit hash (Paste the output of `git rev-parse HEAD` here.)
3. Build config: (Paste the content of config.mk, or the build command.)
- Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

Thanks!

**Comment by lupesko** [comment]
@nswamy please label as "Scala" "Bug"
@lanking520 @andrewfayres @ddavydenko who are working on the Scala API

**Comment by lanking520** [comment]
Adding DataDesc in this PR: https://github.com/apache/incubator-mxnet/pull/11844
