### ISSUE TITLE
What's the difference between Context('cpu') and Context('cpu_shared')?

### ISSUE THREAD

**Issue by karlind** [apache/incubator-mxnet#12158]
When I try to write a custom `batchify_fn`, I find `default_mp_batchify_fn` uses a `Context('cpu_shared', 0)`. I searched document and find almost no description about that.
Comment says it saves memory. But i want to know what's the difference between `Context('cpu')` and `Context('cpu_shared')`. Also how to use it.
Thanks for help.

**Comment by moveforever** [comment]
cpu_shared is context where NDArray is allocated in shared memory.

**Comment by vdantu** [comment]
@mxnet-label-bot [Question]

**Comment by ThomasDelteil** [comment]
@karlind cpu_shared in indeed memory allocated in shared memory rather than the ram allocated to the process running the script.  It should really only be used for data loading purposes to share data between processes.

Please reopen the issue if that doesn't answers your question. @yzhliu  please close the issue
