### ISSUE TITLE
MNIST Handwritten Digit Classification - Missing Page

### ISSUE THREAD

**Issue by rozaliyaeverstova** [apache/incubator-mxnet#12673]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)
MNIST Handwritten Digit Classification[https://github.com/apache/incubator-mxnet/blob/4236b985ea09e7776920376a0ce347316a37e19e/tutorials/python/mnist.html] is missing, giving 404 error. Does this link have the same tutorial: https://mxnet.incubator.apache.org/tutorials/python/mnist.html? 
## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
I'm using Python

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by vandanavk** [comment]
@mxnet-label-bot [Doc, Website]

@aaronmarkham

**Comment by aaronmarkham** [comment]
Yes, those should be the same tutorial, or at least the one on the website is the very latest. Whatever that old link was pointing to was some old version of the tutorial. Please let me know if there's a broken link somewhere that can be updated.

Each markdown tutorial in Github /incubator-mxnet/docs/tutorials/ is converted to html and published on the website: https://mxnet.incubator.apache.org/tutorials/index.html

Rather than look at the markdown versions on Github, I'd browse tutorials (and docs generally) from the website and use the notebook download buttons that are provided on most of them. 
![2018-09-26_13-15-30](https://user-images.githubusercontent.com/5974205/46106715-53306f00-c18e-11e8-938d-b9b769049a58.png)

**Comment by aaronmarkham** [comment]
Github content gets removed. I can't tell why or how in this case. Maybe an deleted branch? But if there's a referring link on the website pointing to that... that's something that can get fixed. 

Licensing is Apache 2.0.

**Comment by nswamy** [comment]
@rozaliyaeverstova thanks for reporting, please refer to the website for downloading the notebook as @aaronmarkham suggested. I am closing this as not an issue, feel free to play with mxnet and bring to our notice issues you may find.
