### ISSUE TITLE
Module.predict(): different behaviour with caffe's net.forward()?

### ISSUE THREAD

**Issue by zeakey** [apache/incubator-mxnet#12838]
It seems that mxnet's `Module.predict(data)` automatically performs a channel switch (eg. RFB2BGR).

I have two identical networks, say `mx_net` and `caffe_net`, in mxnet and caffe respectively, I've mannually checked all the parameters
are identical.

I found that he outputs of the two nets are different by:
```
mx_output = mx_net.predict(data)
caffe_output = caffe_net.forward(data)
```

Interestingly,  if I manually switch channel of the data for mxnet alone, I got identical outputs:
```
caffe_output = caffe_net.forward(data)
data = channel_switch(data)
mx_output = mx_net.predict(data)
```

So is it real that MxNet performs an automatic channel switch inside the `Module.precit()` routine?

If so, can someone point out where does this happen in the source code?

**Comment by lanking520** [comment]
@zeakey I tried to dig in and found a piece of source code for you [here](https://github.com/apache/incubator-mxnet/blob/225f71f744ac5e7bd29868b6d3ba0e4fe2527c43/python/mxnet/module/base_module.py#L317). This is a very interesting question though, maybe you can also try file this issue here: 

English: https://discuss.mxnet.io/
中文: https://discuss.gluon.ai/
@eric-haibin-lin here to see if we can find something interesting here.

@mxnet-label-bot please add [question, python]

**Comment by zeakey** [comment]
@lanking520 I found the evil. Actually I'm working on a project copied from caffe. The author switched the channels of **kernel of the input layer** when migrating from caffe to mxnet.

I close the issue.
