### ISSUE TITLE
waitforall() hides errors

### ISSUE THREAD

**Issue by samskalicky** [apache/incubator-mxnet#13234]
mx.nd.waitforall() doesnt check for errors and rethrow any that have occurred users will get an error when reading the output data. But I ran into an issue where I was gathering performance data, measuring elapsed time over an inference via model.forward() and mx.nd.waitforall() but I had hit an error and it was being hidden by waitforall(). I would have gotten the error had I actually read the output data, though. 

For this issue, we should fix waitforall() to have the ability to check for errors on each of the outputs.

**Comment by anirudh2290** [comment]
this is by design and has been documented in the PR: https://github.com/apache/incubator-mxnet/pull/9681 . The waitforall is generally used for synchronization and benchmarking purposes. If you want to throw the exception you can call wait to read on the variables before or after the waitall call. Adding waitall support requires a global exception ptr and complicates the implementation. To workaround you should read the the output data before or after caliing waitall.

**Comment by lupesko** [comment]
@mxnet-label-bot add [Feature Request]

**Comment by lupesko** [comment]
@mxnet-label-bot add [NDArray]
