### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by gnujimmik** [apache/incubator-mxnet#1332]
Hello, I am working with csv image data and I'd like to augment data using mxnet. I used mxnet.io.CSVIter for the current dataset. But it looks like I need to change or convert dataset to .rec? to use mxnet.io.ImageRecordIter. Are there ways to deal with this? Thank you in advance

**Comment by piiswrong** [comment]
Subclass csviter and implement your own data augmentation in python.

**Comment by gnujimmik** [comment]
Thank you for prompt reply. But I don't get it what you have replied. So I need to make my own data augmentation tools, meaning that ImageRecordIter can't be used in this case?

**Comment by piiswrong** [comment]
If you want to use ImageRecordIter, you can transfer you data into .rec format with mx.recordio.MXRecordIO.

**Comment by axlesor** [comment]
I am also interested in the same issue due to kaggle data science bowl, and I have tried to subclass csviter but I don't think it is written for that purpose:
class CSVIterAug(mx.io.CSVIter):
    def Next(self):
        super().Next()
the error is: TypeError: function() argument 1 must be code, not str
I can make it compile by doing:
class CSVIterAug(mx.io.CSVIter(data_csv="./local_train-data.csv", data_shape=(30, 64, 64), label_csv="./local_train.csv", label_shape=(600,), batch_size=32)):

This  just does not complain but stil cannot able to call Next inside subclass.
Also inside src/io/iter_csv.cc, CSVIter has private members instead of protected which makes it difficult subclass it. Please let me know if subclassing possible but it seems needs a fix.
Thanks

**Comment by hoaphumanoid** [comment]
How can this be done in R? It would be related to #3079

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by TriLoo** [comment]
@axlesor  It seems that you should subclass `MXDataIter`  instead of `CSVIter` as the MXNet Docs said:

> This iterator (MXDataIter) is the Python wrapper to all native C++ data iterators, such
    as `CSVIter`, `ImageRecordIter`, `MNISTIter`, etc. When initializing
    `CSVIter` for example, you will get an `MXDataIter` instance to use in your
    Python code.  

But I still do not know how to add the augmentations into my the derived class. Do you have any advise ?
