### ISSUE TITLE
C API should *never* call abort()

### ISSUE THREAD

**Issue by mika-fischer** [apache/incubator-mxnet#13956]
## Description
C-API functions should catch and report *all* errors instead of calling `abort()` for some errors.

## Environment info (Required)

This is independent of the environment and the problem is present in all releases and the master branch.

## Minimum reproducible example

Basically all uses of the `CHECK...` macros in functions called (even indirectly) from any of the C-API functions are problematic since in case they fail the error cannot be caught by the library user and mxnet just aborts the whole process (via `dmlc::LogMessageFatal`). This is unacceptable for any library…

It might be infeasible to achieve this library-wide. But at least simple user-input errors in `src/c_api` should most definitely not use `CHECK_...` for anything.

One example:
https://github.com/apache/incubator-mxnet/blob/eebdd5f644e953da76ac35a898992ef5c83d3f30/src/c_api/c_predict_api.cc#L130

This should not call abort(), but throw a normal exception so that the library user can handle the error appropriately...

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Bug, c api]

**Comment by stephenrawls** [comment]
I can add a second issue if desired, but I'd like to point out that the C++ API has the same problem.

https://github.com/apache/incubator-mxnet/blob/master/cpp-package/include/mxnet-cpp/executor.hpp#L77-L83

I am using the raw C API (i.e. not the C predict API) partly to avoid having abort called on me.

**Comment by mika-fischer** [comment]
I'll note that even the raw C API (i.e. not the C predict API) has this problem in quite a few places, though they seem to be less easy to trigger.

E.g. https://github.com/apache/incubator-mxnet/blob/0a45e1a222637c7dee29511cbfc43e594571933b/src/c_api/c_api_executor.cc#L358

**Comment by stephenrawls** [comment]
Good point...lots of places to clean up if we want to remove the possibility that abort() gets called on us.

Turns out it's also in the underlying library code implementing e.g. operators:
https://github.com/apache/incubator-mxnet/blob/0d480fbe1534d1c1228bf2c7470018ae06cbac37/src/operator/tensor/init_op.h#L121-L123

I am in the process of putting MxNet into a production environment, and it would be nice if it didn't have the ability to unexpectedly abort() the process it's running in. I guess this is a bigger task than I initially thought.

**Comment by szha** [comment]
@mika-fischer @stephenrawls thanks for the suggestions. Since this requires potentially large change, I'd suggest that we get more attention on this by writing to [dev@mxnet.apache.org](https://lists.apache.org/list.html?dev@mxnet.apache.org).

**Comment by szha** [comment]
By default, those checks should be throwing instead of calling `abort()`.
https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/logging.h#L25-L26

It will abort only when `defined(_LIBCPP_SGX_NO_IOSTREAMS)`
https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/logging.h#L351
or when `DMLC_LOG_FATAL_THROW` is explicitly set to 0.
https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/logging.h#L362

Since the build logic of mxnet itself uses the default setting, I'd like to see how and in what scenarios you trigger either the first or the second case, after which we can try to come up with the fix necessary.

**Comment by stephenrawls** [comment]
Good catch, sorry for the confusion. Can't speak for @mika-fischer, but as for me, I dug through the various layers until I saw `abort()` in the code and didn't pay close enough attention to the #if/#elif preprocessor declarations.

My other complaint about the c++ api is that it doesn't always check the return status of its C API calls. But that issue is much easier to detect and fix, I will put in a separate Issue / Pull Request about that.  (e.g. see here: https://github.com/apache/incubator-mxnet/blob/master/cpp-package/include/mxnet-cpp/operator.hpp#L137-L139)

**Comment by mika-fischer** [comment]
Yes, same here. I think I've seen the pip installed mxnet abort on me before and the stack trace in the error message confused us. But in fact an exception is thrown as you say. So this can be closed. Sorry for the noise.

**Comment by leezu** [comment]
> After all replacements due to macro expansion and the defined unary operator have been performed, all remaining identifiers and keywords, except for true and false, are replaced with the pp-number 0

https://stackoverflow.com/a/5085425/2560672

Thus it is not true that `DMLC_LOG_FATAL_THROW` needs to be explicitly set to 0. Rather, if `DMLC_LOG_FATAL_THROW` is unset, `DMLC_LOG_FATAL_THROW == 0` will evaluate true during preprocessing at least if the preprocessor implements the standard correctly. Some older preprocessors may not have conformed to standard and this logic may have thus appeared to work.

It certainly does not work on GCC7 or Clang 9..

**Comment by szha** [comment]
Thanks for fixing it @leezu
