### ISSUE TITLE
FP16 support for topK 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#14125]
TopK doesn't support fp16 inputs.

**Comment by stephenrawls** [comment]
+1

This is annoying for us because we need to use topk in our CRF Viterbi decoding during inference (for k-best Viterbi).

Because topk doesn't support float16 this means we have to convert from float16 to float32 before doing k-best Viterbi decoding. Since this is the most time consuming part of inference, we would prefer to be able to benefit from float16 operations here.

**Comment by eric-haibin-lin** [comment]
related issues: https://github.com/apache/incubator-mxnet/issues/12705 https://github.com/apache/incubator-mxnet/issues/11156 https://github.com/apache/incubator-mxnet/issues/11061
