### ISSUE TITLE
NDArray C++	construct problem 

### ISSUE THREAD

**Issue by songziqin** [apache/incubator-mxnet#14129]
I use MXnet in C++. I want to construct  a new NDArray  object through a vector object. I use the  NDArray (const std::vector< mx_float > &data) function.

vector<mx_float> v;
for(int index=0;index<10;index++)
     v.push_back(0.01);
NDArray nd_array(v);
and I do a test, what surprise me is  nd_array.Size() != v.size()
I am very confused.

**Comment by lanking520** [comment]
@songziqin Could you please print the result, curious about the outcome

**Comment by leleamol** [comment]
@songziqin ,

The implementation of constructors NDAarray(const vector<mx_float>&data) and NDArray(const mx_float* data) in c++ API (cpp-package/include/mxnet-cpp/ndarray.h) is incorrect.  These constructors call MXNDArrayCreateNone() API that creates an empty NDArrayHandle which is uninitialized. In order to create and store data in an NDArray object successfully, we need to have the context (cpu or gpu) and shape dimensions.

We should remove these constructors as they are not very helpful and incorrectly implemented.

The right way to initialize the above NDArray is as follows:

`NDArray nd_array(v, Shape(v.size(), 1), Context::cpu());
`

I hope this helps.

**Comment by songziqin** [comment]
@leleamol 
thanks a lot.it is really helpful.

**Comment by songziqin** [comment]
@leleamol  I find the NDArray object function SyncCopyFromCPU,it cost much time, I wonder if there is a quicker function can do the same thing.

**Comment by leleamol** [comment]
@songziqin,
The SyncCopyFromCPU() function available in C++ API is a wrapper on underlying MXNDArraySyncCopyFromCPU() implementation.  If the context remains the same, the copying operation should be faster.

You can try NDArray::Copy(context& ctx) or NDArray::CopyTo(NDArray *other) functions to create a copy of existing NDArray.  With the first function, you can change the context of resultant NDArray.
Both these functions use "'_copy" operator.

If the issue with NDArray initialization is addressed, I would suggest closing this issue. If there is question about performance, we can open a separate issue as "feature request/enhancement". This is for better trackability.

**Comment by leleamol** [comment]
@mxnet-label-bot [Pending Requester Info]
