### ISSUE TITLE
c/c++ multiple threads inference problem

### ISSUE THREAD

**Issue by JohnLee168** [apache/incubator-mxnet#14260]
Hi, I have a question for multiple threads inference in c/c++.
The server uses 10 threads to handle request images from clients, and create 20 PredictorHandles(a PredictorHandle pool) to inference. 
When server recv one image in a thread, server chooses an available PredictorHandle(not in use) from the PredictorHandle pool to inference. Each PredictorHandle is only used in one thread, but one thread can choose different  PredictorHandle from the pool. Is this situation thread-safe? 
1. handle created by MXPredCreate() not by MXPredCreateMultiThread()
2. I got thread dead lock sometimes by MXPredForward() if I reuse PredictorHandle created before
3. If I create PredictorHandle every time when used, it goes fine.

**Comment by leleamol** [comment]
@JohnLee168 based on my understanding and documentation the MXPredCreateMultiThread() can be used only when the EngineType is NaiveEngine.

It is possible to reuse  PredictorHandle created by MXPredCreate() in a single threaded environment by calling MXPredForward().
In case of multi-threaded environment, if you want to reuse PredictorHandle, you would have to keep the operations MXPredSetInput(),  MXPredForward() and MXPredGetOutput() in the critical region protected by exclusive lock. 

Since this is a question, please submit them on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
 I would propose to close this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
 Thanks!"

@mxnet-label-bot add [Question, C API, Thread Safety]

**Comment by JohnLee168** [comment]
> @JohnLee168 based on my understanding and documentation the MXPredCreateMultiThread() can be used only when the EngineType is NaiveEngine.
> 
> It is possible to reuse PredictorHandle created by MXPredCreate() in a single threaded environment by calling MXPredForward().
> In case of multi-threaded environment, if you want to reuse PredictorHandle, you would have to keep the operations MXPredSetInput(), MXPredForward() and MXPredGetOutput() in the critical region protected by exclusive lock.
> 
> Since this is a question, please submit them on MXNet discussion forum (https://discuss.mxnet.io), where it will get a wider audience and allow other to learn as well.
> I would propose to close this issue now in favor of the discussion forum issue you will file, please feel free to re-open if closed in error.
> Thanks!"
> 
> @mxnet-label-bot add [Question, C API, Thread Safety]

Thanks for your reply.
So, you mean either I use one thread to inference, or use multiple threads which 
MXPredSetInput(), MXPredForward() and MXPredGetOutput() shoudle be locked(MXPredSetInput(), MXPredForward() and MXPredGetOutput() functions can only be running in one thread at a time), Is that right?
I created a new topic on forum. And i'll close this issue. Thanks for your help.

**Comment by leleamol** [comment]
@lanking520 based on above comment, we can close this issue.
