### ISSUE TITLE
[Discussion] the condition semantics of mxnet_option. 

### ISSUE THREAD

**Issue by yajiedesign** [apache/incubator-mxnet#14640]
current ,If the `mxnet_option` condition is not satisfied, this option will be turned off ,not setting the default value off.
But the current conditions in `mxnet_option` seem to want to set default values. Are we going to modify `mxnet_option`?

**Comment by TaoLv** [comment]
+1 for changing `mxnet_option`. We met issue when build mxnet on Windows and seems `-DUSE_MKLDNN=1` in command line will be overwritten by `mxnet_option`. @yinghu5

**Comment by yinghu5** [comment]
+1, in details, we are trying use cmake to build mxnet with MKLDNN on windows 
Cmake  the command line:  cmake -G "Visual Studio 14 Win64" .. -DUSE_BLAS=open -DUSE_LAPACK=1 -DUSE_MKLDNN=1 -DCMAKE_BUILD_TYPE=Release

we expect the  -DUSE_MKLDNN=1 can overwrite the USE_MKLDNN 
But in Cmakelist.txt file of Mxnet , line 33 . 

-mxnet_option(USE_MKLDNN           "Use MKLDNN variant of MKL (if MKL found)" ON IF USE_MKL_IF_AVAILABLE AND (NOT APPLE) AND (NOT MSVC) AND (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64") AND (NOT CMAKE_CROSSCOMPILING))

It doesn't work under MSVC + windows,  because it was limited to "NOT MSVC"    and   CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")  should be AMD64. 
As a result,  anyone can't build mxnet under windows whatever (even with -DUSE_MKLDNN=1)

We expect the external user define like -DUSE_MKLDNN=1 can overwrite the   mxnet_option

currently, as workaround, we change the line as below. 
 
+mxnet_option(USE_MKLDNN           "Use MKLDNN variant of MKL (if MKL found)" ON IF USE_MKL_IF_AVAILABLE AND (NOT APPLE)  AND (NOT CMAKE_CROSSCOMPILING) AND ((CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64") OR  (CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")))

thanks

**Comment by TaoLv** [comment]
Hi @yajiedesign , do you have any plan to improve mxnet_option now? We found that actually MKL-DNN backend is not built and tested in CI for Windows.

**Comment by yajiedesign** [comment]
https://github.com/apache/incubator-mxnet/pull/14743
