### ISSUE TITLE
[Website] Function parameters display inconsistent

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#16350]
On the page Routines
For certain group of functions, function along with its parameters are displayed
1. Sort and search - https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/routines.html#sort-and-search
2. Neural Network - https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/routines.html#neural-network
3. Miscellaneous - https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/routines.html#miscellaneous

However, for rest of the groups, parameters are not displayed.

Would be great to have one place where there are all Operators (along with their operators)

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [Website]

**Comment by ChaiBapchya** [comment]
@aaronmarkham 
Use-case: In previous website, on 1 single page, I could search for all operators that have specific parameter "index". 
But now I can't.

**Comment by aaronmarkham** [comment]
It would seem that the signatures have been explicitly turned off with `:nosignatures:`.
https://github.com/apache/incubator-mxnet/blob/master/docs/python_docs/python/api/ndarray/routines.rst
I can't tell you why some were left with signatures and some were not other than I recall seeing problems with sphinx throwing duplicate ID warnings. Maybe that's why? You can try it out and remove the nosig thing and see what happens... if that's the desired output and if it doesn't add warnings, because we still need to turn "warnings as errors" back on so that PRs are not added that break the generation of the API docs.


> @aaronmarkham
> Use-case: In previous website, on 1 single page, I could search for all operators that have specific parameter "index".
> But now I can't.
These pages were somewhat hand-crafted to display the different functions, so I suppose you could create a page that has all ops and sigs on it.

**Comment by ChaiBapchya** [comment]
Will be fixed by @ThomasDelteil #16392

**Comment by ChaiBapchya** [comment]
Closing since fixed
