### ISSUE TITLE
dist_async slower than dist_sync

### ISSUE THREAD

**Issue by lispc** [apache/incubator-mxnet#1642]
Hi, I tested the speed of multi-machine training with the following command:

```
../../tools/launch.py -n 2 -H hosts python train_imagenet.py --data-dir /mnt/ficushaiti/zzhang/data/mxnet/imagenet/rec/ --gpus 0,1,2,3,4,5 --batch-size 960 --kv-store dist_(a)sync
```

And I found that with "dist_sync", the total speed is 1070 samples/s, but with "dist_async" the speed is 860 samples/s.
Then I tried to fix the problem. I changed the code in src/kvstore/kvstore_dist_server.h from

```
      } else {
        // async push
        exec_.Exec([this, key, &recved, &stored](){
            CHECK(updater_);
            updater_(key, recved, &stored);
          });                                                                                                                                                               
        server->Response(req_meta);
        stored.WaitToRead();
      }   
    } else {
      // pull

```

to 

```
        } else {
          NDArray temp_data = recved.Copy(Context());
          // async push
          exec_.Exec([this, key, temp_data, &stored](){
              CHECK(updater_);
              updater_(key, temp_data, &stored);                                                                                                                            
            }); 
          server->Response(req_meta);
          stored.WaitToRead();
        }   
      } else {
        // pull
```

then the problem was solved ( 'dist_async' gets the same speed as 'dist_sync' ).

So I wonder
(1) why is 'dist_async' slower than 'dist_sync'?
(2) Is my change right?

The environment:
2 Server with Ubuntu 12.04, each with 6 TitanX
Network is 1Gbps

**Comment by piiswrong** [comment]
Could you propose your change as a PR and we'll review it.
Thanks.
@mli

**Comment by mli** [comment]
i think your codes are right if `Copy` do the actually memory copy, rather than just pass the pointer.

the reason might due to the updater's overhead is not small. in sync_dist, there is only one update for each layer in a minibatch, while for async, there are 12 updates. copying `recved` decouples the updating on the same key and therefore improve the performance. 

however, your method might only improve the performance if that layer size is small, e.g. convolution layer. while for big layers such as fully connected, the extra memory copy might be pretty big. 

a possible solution is, copy only if the recved size is `< bigarray_bound_`, which is defined at https://github.com/dmlc/mxnet/blob/master/src/kvstore/kvstore_local.h#L28

could you please do the following two things

1. confirm that `.Copy` will do the actual memory copy
2. propose a PR to enable your trick if `recved.size < bigarray_bound_`

thanks
