### ISSUE TITLE
Just use fp16 is slower than mixed_precision! Why?

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [apache/incubator-mxnet#16531]
Just use fp16 is slower than mixed_precision! Why?

**Comment by anirudh2290** [comment]
By faster you mean convergence ? Can you elaborate on what is your use case. Are you running it for training or inference ? Can you provide reproducible script ? Its possible that convergence may be slower with all fp16 because certain reduce operators need to run in FP32 mode to retain good accuracy.

**Comment by ZHAIXINGZHAIYUE** [comment]
@anirudh2290 I mean the train speed. mixed_precision: 1000 samples/s, just single fp16: 900 samples/s

**Comment by szha** [comment]
Hi @ZHAIXINGZHAIYUE, please pay attention to the request for your script as it's impossible for others to help without knowing your workload. Thanks.

**Comment by ZHAIXINGZHAIYUE** [comment]
it is influenced by kvstore(local or device).
