### ISSUE TITLE
mxnet official website http://mxnet.incubator.apache.org/get_started display error

### ISSUE THREAD

**Issue by tashaxing** [apache/incubator-mxnet#16784]
[http://mxnet.incubator.apache.org/get_started](http://mxnet.incubator.apache.org/get_started)

the mxnet official get started page is blank, I have tried chrome and safari browser, but it still displays blank page and show nothing

**Comment by leezu** [comment]
Could it be related to the Chinese firewall? Have you tried with a VPN?

**Comment by tashaxing** [comment]
> Could it be related to the Chinese censorship? Have you tried with a VPN?

No, I have tried VPN, but it is still the same
The problem is that the web page header and footer could be normally displayed, just the center content of how to install or get started not displayed well --- totally blank

**Comment by leezu** [comment]
Maybe you are blocking Javascript?

**Comment by ys2843** [comment]
This could because we were using Google CDN for JQuery, which is banned in China. Without JQuery loaded, the `get started` page displays exactly like this 
> The problem is that the web page header and footer could be normally displayed, just the center content of how to install or get started not displayed well --- totally blank

Since we have already changed to host JQuery locally, this won't be a problem any more. Issue could be closed. @sandeep-krishnamurthy @aaronmarkham
