### ISSUE TITLE
CUDA 10.2 Python wheels

### ISSUE THREAD

**Issue by RuRo** [apache/incubator-mxnet#17058]
## Description
There is currently no cuda 10.2 support for prebuilt Python wheels. (`mxnet-cu102` and `mxnet-cu102mkl`)

It would be greatly appreciated if you could add these versions to your CI.

**Comment by RuRo** [comment]
So... neither the `cu102`, nor the `cu102mkl` versions are currently available on PyPI. Are we waiting for the next release? Is there an ETA or something?

**Comment by leezu** [comment]
@RuRo only stable and RC releases are published on Pypi. You can download pre-releases from pip install https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/dist/2019-12-29/dist/mxnet_cu101-1.6.0b20191229-py2.py3-none-manylinux1_x86_64.whl

Unfortunately the nightly build pipeline publishing to https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/dist/2019-12-29/dist/mxnet_cu102-1.6.0b20191229-py2.py3-none-manylinux1_x86_64.whl is broken since December 29, slightly before Cu102 builds were enabled.

@samskalicky could you please comment here once the build pipeline is fixed?

**Comment by uday60** [comment]
Waiting for builds for 10.2

**Comment by samskalicky** [comment]
@mxnet-label-bot add [CI]

**Comment by larroy** [comment]
Let's not close this issue if it's not fixed for the user.

**Comment by josephevans** [comment]
Thanks for the suggestion, noted. We will track this.

**Comment by leezu** [comment]
cu102 nightly convenience builds are now available at https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/index.html thanks to @samskalicky
