### ISSUE TITLE
Cache CUDA modules when building Mxnet 

### ISSUE THREAD

**Issue by cyrusbehr** [apache/incubator-mxnet#17158]
I am trying to build Mxnet with GPU support using the following options:

```
cmake -DUSE_CUDNN=1 -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DCMAKE_BUILD_TYPE=Release -DBLAS=open -DUSE_OPENCV=OFF -DUSE_CPP_PACKAGE=ON -DENABLE_CUDA_RTC=ON ..
```
Currently, the build takes quiet long (~3 hours). I've noticed that the majority of the time is spent building the Cuda modules. 

For my use case, I'll be rebuilding the library often (as part of my CI pipeline) but would like to reduce the build time. Is there some way to run an incremental build which caches these Cuda modules (as they are relatively unchanging) and re-uses them between builds to speed things up?

**Comment by yajiedesign** [comment]
You can try ccache in linux.

**Comment by leezu** [comment]
1) Use ninja instead of make. For that specify `cmake -DNinja [...]` and use `ninja` instead of `make -j`.
2) Use a single a single cuda compute architecture. With https://github.com/apache/incubator-mxnet/pull/17031 you only need to set `-DMXNET_CUDA_ARCH=7.0` (as an example), but until it is merged, you need to set multiple variables. See the commit message at #17031 for the variables you currently need to set. If it's not urgent, you can wait a few days until #17031 is merged.

**Comment by cyrusbehr** [comment]
Excellent thank you, I will give these a try

**Comment by leezu** [comment]
@cyrusbehr FYI, #17031 is merged.
