### ISSUE TITLE
Outdated mxnet nightly build wheel instructions 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#17537]
The mxnet nightly pip wheel instructions are outdated. The latest wheels are available at https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/index.html 

Shall we update the website with this link? Or maybe at least the static links to latest builds

**Comment by szha** [comment]
@samskalicky this page doesn't seem to work when accessed from the alias https://repo.mxnet.io/dist/index.html

**Comment by samskalicky** [comment]
@szha you are correct, the way Javascript XMLHttpRequest works the page and links must be in the same domain as the one the page is accessed from. So either we do it at https://apache-mxnet.s3-us-west-2.amazonaws.com or we do it at https://repo.mxnet.io but we cannot do both at the same time. 

If we are officially blessing this page and making it official we can switch it. Otherwise if the community wants to do something different we can leave it and just access it at https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/index.html until the community implements a new solution.

**Comment by eric-haibin-lin** [comment]
Do it at  https://repo.mxnet.io sounds better. The link is easier to remember compared to the other one. @samskalicky @szha what do you think

**Comment by samskalicky** [comment]
Honestly I dont think the link matters. We're going to embed it in the website and wont expect users to remember the URL by heart. There is no static website at https://repo.mxnet.io/ anyway, so there no expectation that the download page should work at that address. 

Honestly I dont think its a big deal which one we access it from since it will be a link in a webpage. 
<a href="https://apache-mxnet.s3-us-west-2.amazonaws.com/">Get Nightly builds here</a>

**Comment by leezu** [comment]
The key problem here is 

> If we are officially blessing this page and making it official we can switch it. Otherwise if the community wants to do something different we can leave it and just access it at https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/index.html until the community implements a new solution.

To obtain that blessing, the builds located at that side should be created from a community controlled (ie. controlled via some configuration files in a public repository) resource. Has the Jenkins CD already replaced the proprietary build pipeline?

**Comment by samskalicky** [comment]
@leezu I dont think that matters. The bucket will contain the nightly pip wheels regardless of where they are built from. If they are built from a proprietary system or a publicly accessible one they will go to the same/similar location in the bucket and the webpage will just show them. 

This is like saying I wont drive a BMW because its built in [Spartanburg, South Carolina](https://www.bmwgroup-plants.com/spartanburg/en.html) instead of [Munich, Germany](https://www.bmw-welt.com/en/locations/plant.html). 

Irregardless, ive started a PR to add the scripts used in the current CodeBuild system: #17550

If having these scripts in the repo is sufficient, we can finish adding the rest of the scripts and updating the CodeBuild projects to execute these scripts. We can also make build logs and other status updates available to the community as well. Heres one build badge for the plain mxnet build flavor:
![](https://codebuild.us-west-2.amazonaws.com/badges?uuid=eyJlbmNyeXB0ZWREYXRhIjoib2ZpVHY3NTdFZEpBZ21VZVFNNVVVUjVWbjJHQVJCRHVlclVkRGFiU2ZuOSsyUXhPazREQkI4dWRGMW0yV1o1bzNZVS9mQTlVRlFUcjlGZk1QMVB2NEhvPSIsIml2UGFyYW1ldGVyU3BlYyI6IkY5RGVkRkZLOTA3TCtEY20iLCJtYXRlcmlhbFNldFNlcmlhbCI6MX0%3D&branch=master)

**Comment by szha** [comment]
CD was fixed but was failing again after #15990 as it didn't take CD into account. http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-mxnet-cd%2Fmxnet-cd-release-job/detail/mxnet-cd-release-job/656/pipeline#step-487-log-408

I think we should focus on fixing and maintaining one solution instead of creating more distraction

**Comment by szha** [comment]
For https://repo.mxnet.io/dist/index.html I did the following:
- fixed the javascript so that it can be accessed from both the above url and the https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/index.html
- added order and filter to the nightly builds table.

The current practice for a fixed url is simply incorrect. The version used is misleading and claims to be an official release version. This is not an acceptable solution so I'm currently working on updating the static links to the same solution as pytorch nightly page such as this: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

**Comment by szha** [comment]
The directory listing files are now available. I updated the https://repo.mxnet.io/dist/index.html with the links. It's now possible to install nightly builds with the same command:
`pip install --pre mxnet -f https://dist.mxnet.io/python/cpu`

Let's update the installation instructions to use the directory listing files.

**Comment by wilderfield** [comment]
@samskalicky Irregardless is not a word...

**Comment by szha** [comment]
According to Apache incubator VP, the nightly builds should not be offered to the public and only developers should have access.
