### ISSUE TITLE
Website defaults to master API documentation

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18429]
Website shows API documentation for master version by default. That's not useful, as most users will run the stable MXNet version and will be confused by breaking changes in MXNet 2 website.

Reference:
https://github.com/apache/incubator-mxnet/issues/18428

**Comment by leezu** [comment]
cc: @connorgoggins can we default to the latest stable branch?

**Comment by ys2843** [comment]
Please note that the traffic to 1.6 version website only account for 0.54% of total traffic according to Google Analytics.( from 01/2020 to present ). 
The problem seems to be the API docs website failed to clearly showing the users what version of docs they are seeing and what is the stable version. 
@sandeep-krishnamurthy

**Comment by ys2843** [comment]
This issue can be closed.
