### ISSUE TITLE
Merge numpy.mxnet.io to MXNet official website

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#18566]
## Description

Migrate all content from numpy.mxnet.io to official mxnet website. Setup redirects appropriately to divert user traffic to mxnet official website.

@ys2843

**Comment by ys2843** [comment]
## Introduction

MXNet Numpy website hosts essential documents about the usage of MXNet APIs, it is important to share these contents with all MXNet community and new users. In this project, a plan for merging [numpy.mxnet.io](http://numpy.mxnet.io/) to MXNet official website is proposed to achieve above goals.

## Problems

Contents from [numpy.mxnet.io](http://numpy.mxnet.io/) should be ported to MXNet official website

## Proposed Solution

Given that MXNet and Numpy website contains similar contents that diverged from a point due to different maintaining teams, we will select the contents with latest updates to host on MXNet website. There are mainly 4 sections on Numpy website, here is a summary of each section compared to MXNet website:

### **Contents on [numpy.mxnet.io](http://numpy.mxnet.io/)**

* *Guide/Getting started with NP on MXNet* : Contains 6 updated version of [Crash Course](https://mxnet.apache.org/api/python/docs/tutorials/getting-started/crash-course/index.html) under `Python/Tutorials/Get Started/Crash Course`, will overwrite current crash course documents

* *Guide/What is NP on MXNet*: These are new contents that should be added to main site, proposed location: `/Python/Tutorials/Get Started/What is NP on MXNet`

* *API/NP on MXNet reference*: New contents about NP API, will be added to main site. Proposed location:  `/Python/Tutorials/Packages/NDArray/``NP on MXNet reference`

* *API/Gluon reference [Deprecated]*: A subset of [current Gluon Tutorials](https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/index.html), will not make it to main site

### Proposed File Changes on MXNet Website

Please see project proposal Quip link.

## Implementation Timeline

July 13th - July 17th - **Migrate all contents from Numpy website to MXNet website**

* Migrate relating rst files to MXNet Python website code, fix incompatible bugs

July 20th - July 24th - **Close down Numpy website and redirect traffic to MXNet website**

* Implement redirect and possible url mapping

## Reference

1. MXNet numpy website: https://numpy.mxnet.io/
2. Numpy website Github link: https://github.com/mli/deepnumpy-doc
3. Project proposal Quip link: https://quip-amazon.com/DBY4APbnpQKa/Merge-numpymxnetio-to-MXNet-Official-Website

**Comment by szha** [comment]
deep numpy was a temporary code name. we cannot continue to use due to trademark. please remove any reference of it and replace with simply "np".

**Comment by ys2843** [comment]
Got it, will do
