### ISSUE TITLE
nightly builds for Linux

### ISSUE THREAD

**Issue by nicolaerosia** [apache/incubator-mxnet#18650]
I see that nightly builds for Linux are missing and adding them would help Linux users test before the actual release.
https://pypi.org/project/mxnet-mkl/1.7.0b20200315/#files
https://pypi.org/project/mxnet/1.7.0b20200315/#files

**Comment by leezu** [comment]
Builds from PyPI were removed due to resource limitations of the PyPI project: https://github.com/pypa/pypi-support/issues/50#issuecomment-562811825

Also, tApache Policy states

> Do not include any links on the project website that might encourage non-developers to download and use nightly builds, snapshots, release candidates, or any other similar package

http://www.apache.org/legal/release-policy.html#what

There are nightly releases that are not intended for the use of the general public but provided as is for the purpose of testing for MXNet and ecosystem developers at https://repo.mxnet.io/dist/index.html

**Comment by nicolaerosia** [comment]
Thank you, I was not aware of that.
I see that all builds from https://dist.mxnet.io/python/mkl are for macosx, all mxnet devs are using MacOS ? I'm looking for an easy way to test the latest build of mxnet MKL on Linux.
If you have a link for the job that builds the release version and pushes to pypi I could take a look and build it myself.

**Comment by leezu** [comment]
@nicolaerosia the naming scheme for `mkl` may be confusing. There are actually no more builds with `mkl`, due to licensing issues. But all builds now by default come with `mkldnn` (or recently renamed to `onednn`). If you like to use MKL as your BLAS library, you need to build from source.
