### ISSUE TITLE
ImageListDataset

### ISSUE THREAD

**Issue by ranjitkathiriya** [apache/incubator-mxnet#18702]
## 

### Steps to reproduce
a = mx.gluon.data.vision.datasets.ImageListDataset(root=train_paths, imglist=None, flag=1)
## What have you tried to solve it?

#18702

**Comment by szha** [comment]
It's unclear under what setting this happened since the bug report template wasn't properly filled, so there isn't much I could do. I confirm that the dataset class is still available here
https://github.com/apache/incubator-mxnet/blob/690132516a0a99337625248772fd44930686a82b/python/mxnet/gluon/data/vision/datasets.py#L365
