### ISSUE TITLE
metric.py change between branches - missing docs in master

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#18725]
## Description
Looks like master and 1.x have different implementations of metric and this has broken the docs in the process.

This is blank:
https://mxnet.apache.org/api/python/docs/api/metric/index.html

Metric is under gluon in master:
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/metric.py

1.6 has it: 
https://mxnet.apache.org/versions/1.6/api/python/docs/api/metric/index.html

1.5 has it:
https://mxnet.apache.org/versions/1.5.0/api/python/metric/metric.html

**Comment by szha** [comment]
@leezu how would you like this module documented?

**Comment by leezu** [comment]
The module should be documented in the same way as any other module on the website. The issue here is that the website build is not tested in PRs and thus it's no surprise to find various parts of the build break. Can we prioritize fixing the root-cause? https://github.com/apache/incubator-mxnet/issues/18732
