### ISSUE TITLE
Decouple oneDNN data structures in MXNet C++ API

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#20196]
## Description
Currently, onednn/mkldnn header is required in ndarray.h header, and thus requires the onednn/mkldnn headers when linking with libmxnet if mkldnn is turned on (see [here](https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/ndarray.h#L41). To mitigate this, we should look for ways to decouple onednn/mkldnn headers from ndarray.

**Comment by leezu** [comment]
ndarray.h is a C++ header that's currently only exposed because the C API is not convenient enough for https://github.com/horovod/horovod/ Nevertheless, removing onednn/mkldnn headers from ndarray.h could still be useful for consumers of the C++ header.

**Comment by mozga-intel** [comment]
Thanks, @szha, @leezu for this issue.

Currently, there are a lot of places, where it is needed. I got a few ideas to discuss. Since we can't define a variable/objects in a header file as an explicitly defined object `const mkldnn::memory::desc &md` and if this type is used by multiple functions: (i.e `Reorder2DefaultAsync` ), then the object might be passed by using a void pointer `const void *md`.  In the same way, each time you call oneDNN function, the `static_cast` is needed to create a particular object.
```
const mkldnn::memory *mem = static_cast<const mkldnn::memory *>(GetMKLDNNData());
```

Therefore, a header might be placed in *cc file. 
Please have a look: #20349

**Comment by anko-intel** [comment]
@szha issue seems to be done, could you close it
