### ISSUE TITLE
Duplicate lines of project(mxnet C CXX) in the CMakeLists.txt file in master branch. 

### ISSUE THREAD

**Issue by TristonC** [apache/incubator-mxnet#20464]
https://github.com/apache/incubator-mxnet/blob/3480ba2c6df02bb907d3a975d354efa8697c4e71/CMakeLists.txt#L9
https://github.com/apache/incubator-mxnet/blob/3480ba2c6df02bb907d3a975d354efa8697c4e71/CMakeLists.txt#L114
@leezu Is it done on purpose?

**Comment by leezu** [comment]
@TristonC good catch. It was removed as part of https://github.com/apache/incubator-mxnet/commit/d101c3c2d81c2e7e813243e163bfc5aa7a0b3aa3 but added back due to revert https://github.com/apache/incubator-mxnet/commit/d52d9c6f802291713db3330d19bb801a7b9854d5 The revert happened due to an unrelated issue (ie. not the duplicate project removal). Would you like to open a PR to remove one of the project lines?
