### ISSUE TITLE
How to run mxnet on GPU clusters?

### ISSUE THREAD

**Issue by yech1990** [apache/incubator-mxnet#2149]
I am trying to run mxnet on nVidia GPU clusters, sugon HPC.  I don't know how to subject the jobs though `qsub`. 

GPU programming is quite new to me. It is there any tutorial I can follow?

**Comment by sxjscience** [comment]
@yech1990 You can directly submit the python script like `qsub -q gpu.q test.py` . Since MXNet requires other linking libraries, you may need to create a new bash script and initialize these environment variables at the beginning. Check the usage guidance of your GPU cluster for more information.
Also, if you want to do distributed training, you need to read the tutorial http://mxnet.readthedocs.io/en/latest/how_to/multi_devices.html and try the examples in https://github.com/dmlc/mxnet/tree/master/example/image-classification.

**Comment by yech1990** [comment]
@sxjscience  thank you very much!
The GPU cluster guidance is out of date, and the administor is not willing to give any help.

Would you please show one line of example for initializing the environment variables.

BTW, do I need to declare any variable in the PBS script if I install python in my own direction without root. For the GPU cluster only has python 2.4.

**Comment by Feywell** [comment]
@yech1990 Hi, I encounter the same question. I want to use cluster, but I don't kown how to edit the pbs script. Can you help me?
Thank you!
