### ISSUE TITLE
warp-ctc question

### ISSUE THREAD

**Issue by mattndu** [apache/incubator-mxnet#2470]
I'm trying to train the warp-ctc model for OCR.  It sounds like it has a lot of potential to be superior even to expensive commercial-based OCR.  I have a couple questions:
1. What results did you get from training the example Captcha images in your training script?  The best I get is ~1% accuracy after the 10 epochs specified in the script:

```
    2016-06-18 15:58:19,872 Epoch[9] Batch [9850]   Speed: 117.62 samples/sec   Train-Accuracy=0.011250
    2016-06-18 15:58:33,475 Epoch[9] Batch [9900]   Speed: 117.62 samples/sec   Train-Accuracy=0.009375
    2016-06-18 15:58:47,102 Epoch[9] Batch [9950]   Speed: 117.42 samples/sec   Train-Accuracy=0.008125
    2016-06-18 15:59:00,734 Epoch[9] Batch [10000]  Speed: 117.37 samples/sec   Train-Accuracy=0.010625
    2016-06-18 15:59:00,734 Epoch[9] Resetting Data Iterator
    2016-06-18 15:59:00,734 Epoch[9] Time cost=2725.628
    iter
    2016-06-18 16:03:31,963 Epoch[9] Validation-Accuracy=0.009469
    2016-06-18 16:03:31,974 Saved checkpoint to "ocr-0010.params"
```
1. Is there any way to make this faster?  Training on a CPU gives me ~117 samples per second, I switch it over to my GPU (GTX 980) and I still only get ~200 samples per second.  I tried multiple CPUs but that fails.

**Comment by arestorres** [comment]
Have you solved this？ @mattndu    I have the same problem, btw my train_accuracy is 0.00 after 10 epochs (using the example script lstm_ocr.py).

**Comment by yajiedesign** [comment]
i am titan x also ~200 samples per second,add batchsize can faster.But the effect is not obvious.And GPU occupancy rate is very low.
I think it's because of the dynamic generation captcha.If the pre generated is completed, it should be very fast.
@arestorres train_accuracy is need some luck,i am train 10 Epoch is 0., i am stop and restart train .2 Epoch train_accuracy  to 0.4..

**Comment by arestorres** [comment]
@yajiedesign  thanks, i'll try it again...

**Comment by sinmaystar** [comment]
@mattndu How can I run this example on CPU? when I run this example it occurs a problem

mxnet.base.MXNetError: [14:15:36] src/storage/storage.cc:43: Please compile with CUDA enabled

can u tell me how can i solve this problem? thanks very much

**Comment by anxingle** [comment]
my  BATCH_SIZE is 320 and run the example on GTX980ti . Speed is about 410 samples/sec and after epoch0,train-accuracy = 0.37 .        
@sinmaystar     Have U edit the contexts = [mx.context.cpu()]  ? Or maybe you should compile on CPU model.

**Comment by luvWY** [comment]
File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource

It sounds like " self.captcha = ImageCaptcha(fonts=['./data/Xerox.ttf'])"  has a error
i dont know ..... because i cant find "./data/Xerox.ttf" 
and i don't know which resource cannot open ..

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
