### ISSUE TITLE
Is there any completed example on distributed yarn

### ISSUE THREAD

**Issue by wallyell** [apache/incubator-mxnet#2499]
The distributed mxnet on apache hadoop yarn cannot be well trained with the data directly read from HDFS. Can anybody offers an example?

**Comment by SupDataKing** [comment]
I had a same problem, expect to solve.

**Comment by qiaohaijun** [comment]
can't read files on hdfs? any more info?

**Comment by SupDataKing** [comment]
It can used on single machine,but not on distributed !   example, if  execute 
   "../../tools/launch.py -n 2 -H hosts python train_mnist.py  --data-dir hdfs://hadoop01:8020/mnist/"
it will be return error like this==>
"CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 192.168.10.2 'export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib::/opt/mpich/lib::/opt/hadoop-2.6.0/lib/native/:/opt/mpich/lib; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9092; export DMLC_PS_ROOT_URI=192.168.10.2; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /home/hadoop/yewei/mxnet-master/example/image-classification/; python train_mnist.py --data-dir hdfs://hadoop01:8020/yaofei/mnist/'' returned non-zero exit status 1
"
"loadFileSystems error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
hdfsBuilderConnect(forceNewInstance=0, nn=hadoop01:8020, port=0, kerbTicketCachePath=(NULL), userName=(NULL)) error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
[10:04:11] include/dmlc/logging.h:235: [10:04:11] src/io/hdfs_filesys.cc:95: Failed to load HDFS-configuration:"

 Otherwise if I exectue "mxnet/tools/launch.py   -n 2 --launcher yarn python train_mnist.py  --data-dir hdfs://hadoop01:8020/mnist/"
It can only running on  single machine with two processes! how to submit on yarn with multiple devices.

**Comment by SupDataKing** [comment]
@qiaohaijun

**Comment by niuchenglei** [comment]
I get the same situation when i try to run "mxnet/tools/launch.py -n 2 --launcher yarn python train_mnist.py --data-dir hdfs://hadoop01:8020/mnist/ ", then if find "if args.cluster == 'local' or args.host_file is None or args.host_file == 'None':" in launch.py, so that means the host file must be specified when use yarn? i'am totally confused.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
