### ISSUE TITLE
how to learn mxnet

### ISSUE THREAD

**Issue by xtuyaowu** [apache/incubator-mxnet#2561]
is everyone can give some suggestion how to learn mxnet.thanks

**Comment by jonasrla** [comment]
Happily there are plenty of resources:
These are the official resources
[mxnet.readthedocs.io/en/latest/tutorials/index.html](http://mxnet.readthedocs.io/en/latest/how_to/index.html)
[mxnet.readthedocs.io/en/latest/tutorials/index.html](mxnet.readthedocs.io/en/latest/tutorials/index.html)
And here are some code examples
[https://github.com/dmlc/mxnet/tree/master/example](https://github.com/dmlc/mxnet/tree/master/example)
[https://github.com/dmlc/mxnet-gtc-tutorial](https://github.com/dmlc/mxnet-gtc-tutorial)

I specially used this last repo to create my own example on a pull request I'm working on. To run it you will need jupyter, because it's a python notebook.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
