### ISSUE TITLE
SSD example has missing files

### ISSUE THREAD

**Issue by lvaleriu** [apache/incubator-mxnet#3805]
Havent you forgotten to add the files related to the scale layer?

Here you can see them in the original mxnet-ssd repository.

![image](https://cloud.githubusercontent.com/assets/927999/20239447/55ac7736-a900-11e6-82ee-49e28e0b286d.png)

Thanks!

**Comment by piiswrong** [comment]
it is modified and these files are no longer needed.
See if you can run the version in mxnet/exmaple

**Comment by lvaleriu** [comment]
I already tried and it doesnt work without the scale layers. I added them
manually and rebuild mxnet and it worked afterwards.

**Comment by piiswrong** [comment]
@zhreshold

**Comment by zhreshold** [comment]
These layers are not required any more here. What error did you get? @lvaleriu

**Comment by zhreshold** [comment]
Well, I want to make it clear that in order to comply the mxnet example style, I made several changes here in the example/ssd, thus the model is now slightly incompatible with the original repo. You will need to modify .params and .json in order to transfer model between these two repos now.  However I don't recommend to do this.

The divergence could be solved when I finally make a change to the original repo. I'm still reluctant to do so because breaking the compatibility in the same repo is not a good idea.

**Comment by lvaleriu** [comment]
You are right. I've messed up the code by including the old weights with
some old train file execution. Sorry for that. So you've gived up your
Scale layer with an existing one from mxnet?

**Comment by zhreshold** [comment]
Yes, the Scale layer was replaced by broadcast_mul.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
