### ISSUE TITLE
im2rec with unchanged = 1 report error when prediction

### ISSUE THREAD

**Issue by ghost** [apache/incubator-mxnet#3855]
Report error when produce image record file train.rec with parameter with unchanged = 1 and test the iterator will report following error:
[23:10:24] /home/jjzhao/mxnet/dmlc-core/include/dmlc/logging.h:235: [23:10:24] src/io/./iter_batchloader.h:83: Check failed: (unit_size_[i]) == (d.data[i].Size())

But if produce train.rec without unchanged=1 will have no such issue, may I know why?

**Comment by zmonoid** [comment]
Another issue is, when for im2rec, it seems that it cannot encode both png and jpg as stated:
    rgroup.add_argument('--encoding', type=str, default='.jpg', choices=['.jpg', '.png'],
                        help='specify the encoding of the images.')

**Comment by zmonoid** [comment]
This is because some grayscale will have dimension error. Using unchanged=0 will have no such error.
We have compared three methods to extract feature:

1. Input is mx ImageRecord, feature extraction using converted caffemodel
2. Input is image, using preprocessing given in notebook finetune example, feature extraction using converted caffemodel
3. Input is image, using caffe to extract feature

The result shows that it has minimal difference:
For one image feature output from relu7 of VGG16, the sums of the 4096 vector are:
1. 8529.88378906
2. 8542.23437500
3. 8542.23339844

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
