### ISSUE TITLE
Can an ImageRecord pack images as formats other than jpg or png?

### ISSUE THREAD

**Issue by gpatsam** [apache/incubator-mxnet#3895]
I have a dataset that consists of millions of int16 images (actual range is about -4000-+4000, ints). To my knowledge, opencv stores and loads jpgs, pngs as uint8 only. [pack_img](https://github.com/dmlc/mxnet/blob/e7514fe1b3265aaf15870b124bb6ed0edd82fa76/python/mxnet/recordio.py#L244) implies that imagerecord can only handle these two format types.

Is there another way to load int16 images for training (I do not wish to convert to uint8)?Tiff, for example, can store this range.
I would also like to utilize the random crop and random mirror functions, as millions of int16 images already take up significant disk space.

Best,
GPS

**Comment by piiswrong** [comment]
it should work. you need to add encoding quality arguments to pack_img

**Comment by jmerkow** [comment]
This looks interesting to me as well. I save these as int32 tiffs with Pillow (int16 does not save properly).  I don't think opencv can read int32 tiffs though, always return NaNs. Also, it looks like you'll need to override the unpack_image [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/recordio.py#L221-L242), since the image gets unpacked into an unsigned type, so you'de need a flag to convert to the correct type.  I'm new to MxNet, is there a good place to store this information? Perhaps the header?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
