### ISSUE TITLE
CPU cocurrency problem

### ISSUE THREAD

**Issue by humeafo** [apache/incubator-mxnet#4001]
environment: 
    ubuntu x64 16.04 LTS with mxnet installed according to the install document using the ubuntu installation script.
 
run the example train_mnist.py on 8 logical cpus with
OPENBLAS_NUM_THREADS=8 
MXNET_CPU_WORKER_NTHREADS=8
MXNET_CPU_PRIORITY_NTHREADS=8

still only 2 logical cpus used, why? why not  get the cpu count at runtime and use them all by default as tensorflow does?

**Comment by piiswrong** [comment]
because by default cpu ops are not multi threaded. Use USE_MKLDNN=1 in config.mk if you want fast cpu performance.

Grabbing all cpu and gpu resources on startup is very unfriendly to other applications. Also most people care more about gpu performance and multithreaded cpu ops actually hurt gpu performance.

**Comment by humeafo** [comment]
ok, now I've known the reasons. but in case when configured without GPUS, maybe it's more friendly to turn on all CPUS, especially for those who are new to mxnet.

**Comment by clcarwin** [comment]
1. Find this file: ```mshadow/tensor_cpu-inl.h```
2. Find this line then uncomment it: ```// #pragma omp parallel for```
3. Delete this line: ```// temp remove openmp, as default setting throttles CPU```
4. Build mxnet with openmp and set OMP_NUM_THREADS
5. All cpu will be used

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
