### ISSUE TITLE
training-accuracy nan

### ISSUE THREAD

**Issue by ArsenLuca** [apache/incubator-mxnet#4253]
When I was training using my own dataset, the training accuracy was shown to be nan when in epoch 8N-1(e.g. epoch 7, 15,23,31....). This makes me feel puzzled....

Also, in the example https://github.com/dmlc/mxnet-notebooks/blob/master/python/how_to/finetune.ipynb, the training accuracy falls to be nan in epoch 6. I was wondering how did this happen?

**Comment by mli** [comment]
because when called `get()` for a `metric`, the count is 0, which is often due to `reset()` is called. it  doesn't not affect model, but sometime annoying.

**Comment by ArsenLuca** [comment]
@mli many thanks，it's really annoying...

**Comment by kli-nlpr** [comment]
same problem. really annoying

**Comment by mangye16** [comment]
same problem. Does anyone know how to fix it?

**Comment by maxenceliu** [comment]
#5528

**Comment by maxenceliu** [comment]
#5528

**Comment by indhub** [comment]
The "Epoch[x] Train-accuracy=xxx" line printed at the end of every epoch gives the impression that the accuracy metric is for the entire epoch. In reality, it is NOT.

For example if an epoch consists of 101 batches and we were printing metrics every 10 batch because callback was created that way, what will be printed as 'Train-accuracy=xxx' at the end of an epoch is actually just the accuracy from a single batch (101'st batch). Printing this as 'Epoch[x] Train-accuracy=xxx' is very misleading.

Ideally we should remove [this](https://github.com/apache/incubator-mxnet/blob/62bf9ec16886434d5e4eac279db19cb18c5c9c45/python/mxnet/module/base_module.py#L535) misleading print statement. But then, I'm sure there is a lot of existing scripts out there that look for this statement. We can't remove this without breaking those scripts. Since this will be a breaking change, let's do it in a major version change.

For now, to avoid the nan error, we can avoid resetting the metrics when processing callback for the last batch. It will be reset at the beginning of the next epoch anyway.

**Comment by srochel** [comment]
Indu - why is this issue still open if PR 10437 fixed the issue?

**Comment by indhub** [comment]
Fixed by https://github.com/apache/incubator-mxnet/pull/10437
