### ISSUE TITLE
nnpack performance

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#4310]
i tried `nnpack` but fount it performs much slower than mkldnn. 

env:  ec2 c4.4xlarge + ubuntu 14.04

i compiled nnpack with `--enable-shared`, and set `use_nnpack=1` and `use_nnpack_num_threads=16`. 

then in the `mxnet/example/image-classification` folder, run `python benchmark_score.py`

it looks like only a single thread is used.

**Comment by mli** [comment]
@carwin

**Comment by tornadomeet** [comment]
i will also test `nnpack` today.

**Comment by tornadomeet** [comment]
@mli @clcarwin  
i jsut found NNPACK is not fast(maybe only convolution support right now), here is my init test on mtcnn which is a small network in face detection.   

| num thread | speed up |
|:-------------| :-----------|
| 4 | 1.13x|
|24| 1.06x|

this seems not normal when increase threads number.
MKLDNN will speedup about 5x , but this is not fair because MKLDNN will exist in conv/pool/softmax/relu..., and NNPACK only owns in conv.  

another, `USE_NNPACK_NUM_THREADS` is not a environment value, this is not so friendly because we need to compile mxnet when change this value. shall we need refactor it?

**Comment by clcarwin** [comment]
@mli @tornadomeet 
I have tested on ```env: ec2 c4.4xlarge + ubuntu 14.04```, the result in Appendix-1. NNPACK's code will run only when batch_size is 1.
When USE_NNPACK_NUM_THREADS=16, the cpu can be up to 200%~300%, it is not only single thread.

NNPACK is not so fast  in 3 reason:
1. We only use NNPACK's conv in mxnet, tornadomeet have said it.
2. NNPACK scale not good when threads increased. Please read the Appendix-3.
3. NNPACK works very well only when c/w/h/kernel_size are big number. Please try Appendix-2 test.py.

@tornadomeet 
In my practice, NNPACK is good at Neural Style or Android MXNet.

Appendix-1
```
mxnet_atlas
network: alexnet
batch size  1, image/sec: 4.359154
network: vgg
batch size  1, image/sec: 0.741868
network: inception-bn
batch size  1, image/sec: 1.972427
network: inception-v3
batch size  1, image/sec: 0.738954
network: resnet-50
batch size  1, image/sec: 1.167965
network: resnet-152
batch size  1, image/sec: 0.482584

mxnet_nnpack (USE_NNPACK_NUM_THREADS=4)
network: alexnet
batch size  1, image/sec: 6.223492
network: vgg
batch size  1, image/sec: 2.236985
network: inception-bn
batch size  1, image/sec: 3.054394
network: inception-v3
batch size  1, image/sec: 0.750914
network: resnet-50
batch size  1, image/sec: 1.173447
network: resnet-152
batch size  1, image/sec: 0.486510

mxnet_nnpack (USE_NNPACK_NUM_THREADS=16)
network: alexnet
batch size  1, image/sec: 6.022573
network: vgg
batch size  1, image/sec: 2.142447
network: inception-bn
batch size  1, image/sec: 2.822085
network: inception-v3
batch size  1, image/sec: 0.751079
network: resnet-50
batch size  1, image/sec: 1.174311
network: resnet-152
batch size  1, image/sec: 0.486705
```

Appendix-2
test.py
```
from common import find_mxnet
import mxnet as mx
import os, sys, time
import numpy as np

data = mx.sym.Variable("data")
net = mx.symbol.Convolution(data=data, num_filter=128, kernel=(3, 3), stride=(1,1), pad=(0,0), workspace=4000)

mod = mx.mod.Module(symbol=net)
mod.bind(data_shapes=[("data" , (1,64,1000,1000))], for_training=False, inputs_need_grad=False)
mod.init_params()

d = np.ones((1,64,1000,1000))
start = time.time()
dataiter = mx.io.NDArrayIter(d)
r = mod.predict(dataiter).asnumpy()
print 'time: ' , (time.time() - start)
```

Appendix-3
result for test.py
```
mxnet_atlas
time:  13.5786809921

mxnet_nnpack (USE_NNPACK_NUM_THREADS=4)
time:  1.2751531601

mxnet_nnpack (USE_NNPACK_NUM_THREADS=16)
time:  1.05738401413
```

**Comment by mli** [comment]
android you mean arm+neon? do you have some benchmark results for it?

**Comment by tornadomeet** [comment]
@clcarwin thanks for this information, i'll add NNPACK support other layers next week(only inference).   

@mli ResNet-v2 may be not speeded up by NNPACK, because `no_bias=True` there, and it seems that NNPACK only support `no_bias+False`,  https://github.com/dmlc/mxnet/blob/master/src/operator/convolution.cc#L42

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
