### ISSUE TITLE
very small mistake in mx-rcnn debug mode

### ISSUE THREAD

**Issue by zhiding** [apache/incubator-mxnet#4633]
A little mistake in Loader.py file Line 304
missing `{}` before `=`
`"len(label_list)={},len(new_label_list)=".format(len(label_list), len(new_label_list))`
url: https://github.com/dmlc/mxnet/blob/master/example/rcnn/rcnn/loader.py#L304
But still awesome code which I have learned a lot from! Thanks.

**Comment by zhiding** [comment]
Also found another mistake in demo.py file Line 42 https://github.com/dmlc/mxnet/blob/master/example/rcnn/demo.py#L42
missing `need_mean=True` params, it should be,
`im_array = transform(im_array, config.PIXEL_MEANS, True)`
When it runs to Line 65, https://github.com/dmlc/mxnet/blob/master/example/rcnn/demo.py#L65
it calls `transform_inverse` func and thus a mean value will be added to each image pixels.
But in `transform` func, the default value of `need_mean` is `False`

**Comment by piiswrong** [comment]
@precedenceguo

**Comment by precedenceguo** [comment]
loader.py line 304 is just a typo.
demo.py line 42 need_mean = True. It is just that resnet does not need mean, p.s. I have used [0, 0, 0] as resnet image mean in later versions.
Could you please try to fix them for us?

I am working on ResNet and coco detection to update this example. Much have been refactored so problems caused by e2e training will then go away.

**Comment by zhiding** [comment]
I will try it. It may takes some time.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
