### ISSUE TITLE
Asynchronous mini-batch allocation for DMA to GPU

### ISSUE THREAD

**Issue by divfor** [apache/incubator-mxnet#4663]
hello, I read this 'http://timdettmers.com/2015/03/09/deep-learning-hardware-guide/' and found the author says lower hardware configuration can achieve very good speed if using asyn mini-batch DMA to GPU.  has mxnet already supported it? or in the TODO?

**Asynchronous mini-batch allocation**

Once your GPU finished computation on the current mini-batch, it wants to immediately work on the next mini-batch. You can now of course, initiate a DMA transfer and then wait for the transfer to complete so that your GPU can continue to crunch numbers. But there is a much more efficient way: Prepare the next mini-batch in advance so that your GPU does not have to wait at all. This can be done easily and asynchronously with no degradation in GPU performance.

CUDA Code for asynchronous mini-batch allocation: The first two calls are made when the GPU starts with the current batch; the last two calls are made when the GPU finished with the current batch. The transfer of the data will be completed long before the stream is synchronized in the second step, so there will be no delay for the GPU to begin with the next batch.
**cudaMemcpyAsync(m_next_batch_X->data, m_next_buffer_X->data, copy_range_bytes_X, cudaMemcpyHostToDevice, m_streamNext_batch_X);
cudaMemcpyAsync(m_next_batch_Y->data, m_next_buffer_Y->data, copy_range_bytes_Y, cudaMemcpyHostToDevice, m_streamNext_batch_Y);**

**cudaStreamSynchronize(m_streamNext_batch_X);
cudaStreamSynchronize(m_streamNext_batch_Y);**

**Comment by piiswrong** [comment]
This should be done by default

**Comment by minazou** [comment]
Hi @piiswrong.
The attached screenshot is training AlexNet in example/image-classification.
As you mentioned, the CPU2GPU copy has been achieved asynchronously as GPU/0 and GPU/1.
However, when I train AlexNet with 8 K80, the speedup compared to 1 GPU is only 3.7x.
Then, after profiling, I find loading data batch blocks the forward/backward operation like screenshot.
Hence, there is lots of idle time for GPUs.
The root cause is that the "crop" operations are only executed on a single **CPU** thread.
How do you think about running "crop" concurrently to improve the performance under multiple GPUs?
I may try to do in my leisure time.
Thanks.

![screen](https://cloud.githubusercontent.com/assets/1085966/22727203/8902b1d4-ee12-11e6-9478-8396e1b75147.png)

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
