### ISSUE TITLE
scalapkg fails to build

### ISSUE THREAD

**Issue by alexy** [apache/incubator-mxnet#4769]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: OSX Sierra

Compiler:

Package used (Python/R/Scala/Julia): Scala

MXNet version:

Or if installed from source: HEAD

MXNet commit hash (`git rev-parse HEAD`): 339270b5c74a6fece333e1aa7566e333a3e8549c

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.artifactId' for ml.dmlc.mxnet:libmxnet-init-scala-${platform}:${libtype} with value 'libmxnet-init-scala-${platform}' does not match a valid id pattern. @ line 77, column 19
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project ml.dmlc.mxnet:mxnet-macros_2.11:0.1.2-SNAPSHOT (/Users/alexy/src/mxnet/scala-package/macros/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.artifactId' for ml.dmlc.mxnet:libmxnet-init-scala-${platform}:${libtype} with value 'libmxnet-init-scala-${platform}' does not match a valid id pattern. @ line 77, column 19
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
make: *** [scalapkg] Error 1

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. build shared library
2. make scalapkg

## What have you tried to solve it?

1. grok how the parameters need to be set...

**Comment by Ldpe2G** [comment]
@alexy you can refer to #4551 and #4469

**Comment by Natural209X** [comment]
@Ldpe2G  I have the same issue, #4551 and #4469 does not really address this question.

In the document it is also confusing:

Use the Prebuilt Binary Package

For Linux users, MXNet provides prebuilt binary packages that support computers with either GPU or CPU processors. To download and build these packages using Maven, change the artifactId in the following Maven dependency to match your architecture:

<dependency>
  <groupId>ml.dmlc.mxnet</groupId>
  <artifactId>mxnet-full_<system architecture></artifactId>
  <version>0.1.1</version>
</dependency>
For example, to download and build the 64-bit CPU-only version for Linux, use:

<dependency>
  <groupId>ml.dmlc.mxnet</groupId>
  <artifactId>mxnet-full_2.10-linux-x86_64-cpu</artifactId>
  <version>0.1.1</version>
</dependency>
If your native environment differs slightly from the assembly package, for example, if you use the openblas package instead of the atlas package, it’s better to use the mxnet-core package and put the compiled Java native library in your load path:

<dependency>
  <groupId>ml.dmlc.mxnet</groupId>
  <artifactId>mxnet-core_2.10</artifactId>
  <version>0.1.1</version>
</dependency>


which does not specifiy which POM the artifactID "mxnet-full_" is in.

Please let me know how to fix.

Thanks.

**Comment by Ldpe2G** [comment]
@javelinjs @CodingCat

**Comment by CodingCat** [comment]
Which version of maven are you using?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
