### ISSUE TITLE
[feature request] mxnet.io.CSVIter data_shape required parameter

### ISSUE THREAD

**Issue by asadoughi** [apache/incubator-mxnet#4869]
I started using CSVIter and noticed data_shape was a required parameter to determine the shape of a given row.
```
csv_iter = mx.io.CSVIter(data_csv="/input/iris.csv", data_shape=(4,), batch_size=k)
```
Is there a sentinel or something I can pass in to flag it as auto-compute? I could write my own helper function to read the file, find the newline and count the commas on the first line, but I'd prefer if mxnet took care of it.

**Comment by Techro-Raj** [comment]
You don't actually have to compute the whole shape. If you want, you can easily do that in a few ways 
In numpy you would do it like this:
`rdata1 = open("filename.csv", 'rb')
data1 = numpy.loadtxt(rdata1, delimiter=",")
print data1.shape`

But you actually don't need to find the total row X column dimension, since it infers the shape. Data_shape actually reshapes each row. For instance if you have 6 features, i.e. 6 columns for each row, you can reshape them as 1,6 or 2,3, etc. I don't really understand the reasoning behind data_shape, but that's all I know.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
