### ISSUE TITLE
Executor API for Python - Not supported anymore? 

### ISSUE THREAD

**Issue by ghost** [apache/incubator-mxnet#5332]
In the latest version of the Mxnet, I don't see any documentation regarding the Executor object. I used to utilize it as a low level calculation tool for my custom architecture. Is the new Module API replacing it? Is it still safe to use Executor class and its methods still? (And I strongly believe that you need to put the Executor object back into docs)

**Comment by jmacglashan** [comment]
Pretty sure this is just an oversight since they recently updated the doc page. It's still in the code and still pretty heavily relied upon as the lowest-level compute machine. `Module` is a high-level interface and has actually been around for a while. (`Module` did, however, replace the previous high-level interface `Model`)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
