### ISSUE TITLE
How to dynamically set "k" in mxnet.symbol.topk ?

### ISSUE THREAD

**Issue by ufukcbicici** [apache/incubator-mxnet#5496]
I have a setting, in which I want to use the mxnet.symbol.topk operator and and get the top k largest elements in a vector, during the feedforward calculation. The problem is, it is not known to me what the k should be in advance; k is generated as the result of a prior operator in the symbolic network. Current specification of the topk operator takes "k" as an hardcoded parameter, in the compile time. Is there a workaround to this, such that I can give k dynamically?

**Comment by sxjscience** [comment]
@ufukcbicici In that case you can use argsort first and manually slice the topk elements using `take` or `batch_take`.

**Comment by ufukcbicici** [comment]
In your suggestion, I still do not know the "k", which top "k" elements to select in compile time.

**Comment by sxjscience** [comment]
@ufukcbicici I've misunderstood the question. I think it cannot be implemented using the current topk since the shape of the output will be dynamic.

**Comment by jmacglashan** [comment]
On top of the shaping issue, the other issue is it's not entirely clear what the gradient for a dynamic k would be (or what would make one useful). I would recommend the following architecture, or something like it, to instead get the effect you want. It has the nice property that the function has a bit of burliness around the edges which lets the gradients "see" whether it's useful to expand or contract k.

First, for your topk function, set its k to always be the maximum selection size you're willing to allow (we'll "softly" select a smaller k next)

Next you want to gate the values of the selected k, which means we want to multiply it by a vector with values between 0 and 1 so that only some of the values get "let through." Furthermore, the gate vector should have a monotonically decreasing property as you go further down the k elements and we want it fairly sharp so most elements are near the value 1 or 0. We want this because if the bottom k - k2 gate values are effectively zero and the top k2 gate values are effectively one, then you have an effective dynamic top k2 parameter.

So the question is how do you generate such a gate vector that is differentiable on some parameter that affects k2? Here is one way.

-Create a constant inds, which is a vector with the value [0, 1, 2, ... k-1] (e.g., what an arange function would produce).

-Create a scalar variable k_alt and broadcast it to size k.

-Create a constant "sharpness" weight, w (choose its value as you desire)

-Set your gate vector to the be the result of sigmoid(w * (k_alt - inds))

The output of that sigmoid will produce a monotonically decreasing vector from 1 to 0. Increasing w will push most of the values near 1 or 0 with the transition from 1 to zero happening over few indices. decreasing w will "smear" the values a bit more and cause the transition from near 1 to near zero happen over more indices. 

Importantly, as the continuous k_alt parameter is increased, more of the k instances pass through the gate (more values near 1) and as k_alt decreases, fewer of the k instances pass through the gate (more values near zero).

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
