### ISSUE TITLE
How to truncate backpropagation in LSTM?

### ISSUE THREAD

**Issue by hyxie6** [apache/incubator-mxnet#5537]
I want to use LSTM to implement a classification task on 20 news group dataset
as described in the paper [Semi-Supervised Sequence Learning](https://papers.nips.cc/paper/5949-semi-supervised-sequence-learning.pdf)
the authors truncated backpropagation up to 400 timesteps from the end of the sequence and clipped the cell outputs and gradient (see section 4)

How can I implement this feature using MXNet?

**Comment by piiswrong** [comment]
try sym.BlockGard

**Comment by HyXieS** [comment]
currently, the rnn network implemented in mxnet does not support clipping operation, will this feature added in future?

how to clip gradient of cell? it seems that after computing the gradient of cell c_t, they apply clipping immediately, instead of computing the whole gradient (through the end of a sequence to the begining) and then apply clipping

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
