### ISSUE TITLE
when I set the kvstore=None, Multi-GPU is faster than One GPU.

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#5697]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:ubuntu14.04

Compiler:g++

Package used (Python/R/Scala/Julia):Python

MXNet version:0.8.0

Or if installed from source:yes

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:2.7

##Problem:
4 GPUs(GTX1080) in one Server.

Multi-GPUs is slower than One GPU. when kvstore='local'

## What have you tried to solve it?
when I set the kvstore=None, Multi-GPU is faster than One GPU.

@piiswrong

**Comment by piiswrong** [comment]
try kvstore = 'device'/'local'/'device_allreduce' etc and use the fastest one

**Comment by piiswrong** [comment]
@mli We should change the defaults

**Comment by starimpact** [comment]
where can i find the kvstore's value options? I can't find any of them , such as 'device', 'device_allreduce',  in the mxnet/python/mxnet/ folder.

**Comment by eyan422** [comment]
发送自我的 BlackBerry 10 智能手机。                                                                                                                                                                                                                发件人： Zhang Ming已发送： Thursday, 6 April, 2017 17:54收件人： dmlc/mxnet答复： dmlc/mxnet抄送： Subscribed主题： Re: [dmlc/mxnet] when I set the kvstore=None, Multi-GPU is faster than One GPU. (#5697)where can i find the kvstore's value options? I can't find any of them , such as 'device', 'device_allreduce',  in the mxnet/python/mxnet/ folder.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dmlc/mxnet","title":"dmlc/mxnet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dmlc/mxnet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@starimpact in #5697: where can i find the kvstore's value options? I can't find any of them , such as 'device', 'device_allreduce',  in the mxnet/python/mxnet/ folder."}],"action":{"name":"View Issue","url":"https://github.com/dmlc/mxnet/issues/5697#issuecomment-292125558"}}}

**Comment by starimpact** [comment]
oh....on another server , ```kvstore='local'``` is faster than ```kvstore=None```. it is strange. why?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
