### ISSUE TITLE
[vote] new navbar color

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#5706]
@zackchase suggested to change the navbar, i cannot tell the new one is much better. so i'd like to have a vote

**Comment by mli** [comment]
current one

![image](https://cloud.githubusercontent.com/assets/421857/24733049/e8cf782a-1a29-11e7-89b6-715bf70e3ab2.png)

![image](https://cloud.githubusercontent.com/assets/421857/24733053/f03d898a-1a29-11e7-9cb7-91de48484efa.png)

**Comment by mli** [comment]
new one

![image](https://cloud.githubusercontent.com/assets/421857/24733059/fde6de2e-1a29-11e7-99e7-034eb725e8d9.png)

![image](https://cloud.githubusercontent.com/assets/421857/24733063/04830186-1a2a-11e7-86d2-209815b50f43.png)

**Comment by jspisak** [comment]
I am having trouble telling the difference as well.

**Comment by eric-haibin-lin** [comment]
I like the new one.

**Comment by matt32106** [comment]
current

**Comment by zackchase** [comment]
The current navbar looks strange on the home page because it blends in to
the background. Notice that any professional site has some visual cue to
distinguish the navbar from the rest of the page.

https://www.amazon.com/
https://www.nytimes.com/

Of course there are multiple ways to do this. But the current design is
unacceptable.

Also we cannot have Bright orange headings for page sections. Warm colors
(orange, red) intuitively signify warnings.

**Comment by reminisce** [comment]
The new one looks better. It makes the nav bar more visible to users on the first page. But the heading could avoid using the same color as nav bar, for example,
https://www.tensorflow.org/api_docs/

**Comment by Godricly** [comment]
Where is the search for new one?

**Comment by zihaolucky** [comment]
vote for the new one.

**Comment by zackchase** [comment]
I think the consensus is that the new navbar color is better but that we
need a new headline color (shouldn't be the same as the navbar color). I
suggest a dark grey.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
