### ISSUE TITLE
MXNet fcnxs examples: GPU memory usage varies during training. 

### ISSUE THREAD

**Issue by KeLipeng** [apache/incubator-mxnet#5748]
When training the fcnxs examples, the GPU memory varies from 3GB to the MAX GPU Memory, which looks like a GPU memory leak problem. Did anybody get the same issue?
Also, how can we see the feature map when testing on an image? I mean, how can I see a specific layer's output without defining it as the output in the symbol file.

**Comment by Godricly** [comment]
1. Same here. It's related to the image size. the symbols are bound each time a new image coming. 
2. The monitor is what you looking for. Or you can define some simple debug symbol.

**Comment by KeLipeng** [comment]
Thanks, I got it. It is the image size that varies the GPU memory usage. (I forget that the input size varies)

**Comment by eric-haibin-lin** [comment]
Similar issue regarding feature map: #5150

**Comment by KeLipeng** [comment]
Thanks, Haibin, I found that before, but actually I am looking for some
method that could enable me to monitor the feature maps without predefining
it as output in symbol file.

Lipeng

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by thomelane** [comment]
@KeLipeng it looks like you now understand the primary issue of variable gpu memory usage, so going to request for this issue to be closed. Just to confirm, you were seeing this effect because the input images were of different sizes, leading to different sized feature maps and thus different amounts of memory used. 

With regards to the secondary question related to inspecting feature maps. You have to specify it as an output to your model with Module API. What problem does this cause? But with Gluon API (before hybridizing) you can inspect feature maps and kernels really easily. Since you have access to the array values you can calculate summary statistics, plot images, etc. Also I'd recommend [this tutorial](https://mxnet.incubator.apache.org/tutorials/vision/cnn_visualization.html) for visualizing CNNs.
