### ISSUE TITLE
What's the shape of x and w of RNNs in cudnn?

### ISSUE THREAD

**Issue by QuantumLiu** [apache/incubator-mxnet#5751]
I'm developing a DL toolbox and plan to use cudnn.
But the shape of x and w of RNNs confused me a lot.In most frameworks,the shape of input tensor is(minibatch,timestep,inputdim),but in `cudnn_RNNsample` it define the `dimA` of `xDesc` by
```
for (int i = 0; i < seqLength; i++) {  
...
      dimA[0] = miniBatch;//batchsize
      dimA[1] = inputSize;//input_dim
      dimA[2] = 1;

```
So,is that means the shape of x is (timestep,minibatch,inputdim)?
And the shape of W(weights) also confused me a lot.

**Comment by sbodenstein** [comment]
The input shape `x` is indeed `[timestep, minibatch, input dim]`. This is a fairly common convention for representing sequences. The weights are represented as a vector of floats. This is necessary because there is an unbounded number of possible weight matrices possible (as you can stack many layers together). I think MXNet recently got a converter that takes the flat vector and returns a dictionary of weight matrices and bias vectors.

**Comment by QuantumLiu** [comment]
@sbodenstein 
Thank you.
I think the weights vector of a lstm layer can be coverted to a shape like `[ input_dim+hiddensize,4*hiddensize]`,but I don't know how do cudnn permute them.

**Comment by QuantumLiu** [comment]
@sbodenstein 
So，the weights can't be used without cudnn?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
