### ISSUE TITLE
nan metrics during SSD training

### ISSUE THREAD

**Issue by realbns2008** [apache/incubator-mxnet#5825]
I use ssd in the example to train a model to identify the Chinese words  in a picture.

encountered 2 problem: 

**1.Problem:** During training i encountered NaN metrics for both cross-entropy loss and smooth-l1 loss.
After setting the clip_gradient parameters for optimization to 5 , the NaN metrics disappeared.
So the NaN metrics is caused by gradient explosion.

**2. Problem:** The cross-entropy metric never convergence！ I have 30000+ training samples. each sample has added some Chinese words generated randomly, and the location of the words are correctly provided to the model.

Can any one help me on the second problem?

.

**Comment by edwardzeng** [comment]
Chinese characters are too many ，so your classes is too large and each class hasn't enough samples.




On 04/13/2017 18:19, realbns2008 wrote:

I use ssd in the example to train a model to identify the Chinese words in a picture.

encountered 2 problem:

1.Problem: During training i encountered NaN metrics for both cross-entropy loss and smooth-l1 loss.
After setting the clip_gradient parameters for optimization to 5 , the NaN metrics disappeared.
So the NaN metrics is caused by gradient explosion.

2. Problem: The cross-entropy metric never convergence！ I have 30000+ training samples. each sample has added some Chinese words generated randomly, and the location of the words are correctly provided to the model.

Can any one help me on the second problem?

.

**Comment by realbns2008** [comment]
may be i'm not saying it clear.
I used model to identify is there any Chinese words exists in the picture.
so there are only 2 classes : 1. 'background', 2. 'has chinese words'

**Comment by edwardzeng** [comment]
SSD can't detect small object. Is your training character size small?




On 04/14/2017 10:13, realbns2008 wrote:

may be i'm not saying it clear.
I used model to identify is there any Chinese words exists in the picture.
so there are only 2 classes : 1. 'background', 2. 'has chinese words'

**Comment by zhreshold** [comment]
How many characters are there on each image in average?
If you are confident that your implementation is correct, make sure the number of objects are reasonable.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
