### ISSUE TITLE
faster-rcnn multi-gpu problem

### ISSUE THREAD

**Issue by niluanwudidadi** [apache/incubator-mxnet#5845]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Ubuntu16.04 

Compiler:gcc 5.4

Package used (Python/R/Scala/Julia):Python

MXNet version:0.9.1

Or if installed from source:yes

## Problem:
I have met a problem in multi-gpu rcnn training,when i use 4 1080, the speed is no faster than 2 gpu, and the terminal report the message "only 4 out of 12 GPU pairs are enabled direct access.The command is python train_end2end --gpu 0,1,2,3. Is the vgg network's reason?when I use resnet the speed is increases linearly with the number of gpu; and is there some parameters should set?

when i use python train_end2end --gpu 0 ,the speed is 5.4 samples/s
when i use python train_end2end --gpu 0,1 ,the speed is 8 samples/s
when i use python train_end2end --gpu 0,1,2 ,the speed is 7.4 samples/s
when i use python train_end2end --gpu 0,1,2,3 ,the speed is 6.4 samples/s

when i use python train_end2end --network resnet --gpu 0 ,the speed is 2.3 samples/s
when i use python train_end2end --network resnet --gpu 0,1 ,the speed is 4.0 samples/s
when i use python train_end2end --network resnet --gpu 0,1,2 ,the speed is 5.0 samples/s
when i use python train_end2end --network resnet --gpu 0,1,2,3 ,the speed is 5.7 samples/s

**Comment by edwardzeng** [comment]
Because the code only support batchsize =1.Exchanging data between GPUs cost much time.




On 04/15/2017 13:56, niluanwudidadi wrote:

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

Environment info

Operating System:Ubuntu16.04

Compiler:gcc 5.4

Package used (Python/R/Scala/Julia):Python

MXNet version:0.9.1

Or if installed from source:yes

Problem:

I have met a problem in multi-gpu rcnn training,when i use 4 1080, the speed is no faster than 2 gpu, and the terminal report the message "only 4 out of 12 GPU pairs are enabled direct access.The command is python train_end2end --gpu 0,1,2,3. Is the vgg network's reason?when I use resnet the speed is increases linearly with the number of gpu; and is there some parameters should set?

when i use python train_end2end --gpu 0 ,the speed is 5.4 samples/s
when i use python train_end2end --gpu 0,1 ,the speed is 8 samples/s
when i use python train_end2end --gpu 0,1,2 ,the speed is 7.4 samples/s
when i use python train_end2end --gpu 0,1,2,3 ,the speed is 6.4 samples/s

when i use python train_end2end --network resnet --gpu 0 ,the speed is 2.3 samples/s
when i use python train_end2end --network resnet --gpu 0,1 ,the speed is 4.0 samples/s
when i use python train_end2end --network resnet --gpu 0,1,2 ,the speed is 5.0 samples/s
when i use python train_end2end --network resnet --gpu 0,1,2,3 ,the speed is 5.7 samples/s

**Comment by niluanwudidadi** [comment]
Thank you! The communication between gpus may be cost too much. @edwardzeng

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
