### ISSUE TITLE
Installation instructions need update

### ISSUE THREAD

**Issue by jkh1** [apache/incubator-mxnet#6305]
Following instructions from http://mxnet.io/get_started/ubuntu_setup.html
MXNet can't be built on Ubuntu 16.04 with the default OpenCV (version 2.4.9) because MXNet 0.9.5 requires at least OpenCV 3.x due to the reference to -lopencv_imgcodecs.
In addition, OpenCV3.1 is not compatible with CUDA8 so OpenCV3.2 is required.

Installing OpenCV3.2-dev following instructions from 
https://github.com/BVLC/caffe/wiki/OpenCV-3.1-Installation-Guide-on-Ubuntu-16.04
resolves the issue.

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04

Compiler: gcc 5.4.0

MXNet version: 0.9.5

**Comment by piiswrong** [comment]
@szha @mli  I thought the test server was running opencv 2.4?

**Comment by szha** [comment]
The image codecs functions were in highgui module in OpenCV2.4 and were moved to imgcodecs in 3.0. It should be compatible as long as you change the -lopencv_imgcodecs to -lopencv_highgui, and it should work with opencv2.

What do you mean by "OpenCV3.1 is not compatible with CUDA8"? Are you using OpenCV for something else? MXNet does not require having a CUDA enabled version of OpenCV.

**Comment by piiswrong** [comment]
can we detect opencv version and link against the correct lib?

**Comment by jkh1** [comment]
"OpenCV3.1 is not compatible with CUDA8": I take this from here: https://github.com/opencv/opencv/issues/6632

**Comment by szha** [comment]
That issue is on opencv_cudaimgproc, which is not a dependency for mxnet

**Comment by szha** [comment]
@sandeep-krishnamurthy turns out the installation instructions have a couple of issues.
* [-lopencv_imgcodecs](https://github.com/dmlc/mxnet/blame/master/docs/get_started/ubuntu_setup.md#L102) in the instruction should not be necessary because of [pkg-config invocation in Makefile](https://github.com/dmlc/mxnet/blob/master/Makefile#L78-L85).
* [These references to openblas](https://github.com/dmlc/mxnet/blame/master/docs/get_started/ubuntu_setup.md#L100-L101) are totally wrong because the [installation guide said to install atlas](https://github.com/dmlc/mxnet/blame/master/docs/get_started/ubuntu_setup.md#L87-L90).

@sandeep-krishnamurthy please fix both cases and send pr. Also please work with @lxn2 to make sure that in the CI the tests would actually capture this type of problems. If these don't capture problems, it means we don't need them.

**Comment by sandeep-krishnamurthy** [comment]
* This page is obsolete - http://mxnet.io/get_started/ubuntu_setup.html and CI tests are not running on this page. We need to remove this page and add a redirection (so search engine links are not broken). I will do that.

* Here is the page we recently worked and improved the installation guide with installation instructions that is being tested on CI - http://mxnet.io/get_started/install.html.

**Comment by szha** [comment]
@sandeep-krishnamurthy how's the progress.

**Comment by sandeep-krishnamurthy** [comment]
PR - https://github.com/dmlc/mxnet/pull/6585

**Comment by szha** [comment]
Seems that this issue has been fixed.
