### ISSUE TITLE
Performance of deep speech is bad

### ISSUE THREAD

**Issue by xinq2016** [apache/incubator-mxnet#6418]
## Environment info
Operating System: ubuntu 14.04
GPU: GTX 1080

Package used (Python/R/Scala/Julia): python

MXNet version: 0.9.5

Or if installed from source: git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive

## Error Message:
I just follow the default configure script in the example of speech recognition with the corpus of librispeech (clean-360 subset).
1. After two epochs, the CER seems to be bad with CER 70%+
![image](https://cloud.githubusercontent.com/assets/20516775/26392528/83c32832-4099-11e7-8bb5-41cdee039e91.png)
![image](https://cloud.githubusercontent.com/assets/20516775/26392541/8d14157c-4099-11e7-9586-d040a846cc7b.png)
![image](https://cloud.githubusercontent.com/assets/20516775/26392566/a5e909e0-4099-11e7-9e8a-3b4ddae0cc1f.png)
![image](https://cloud.githubusercontent.com/assets/20516775/26392580/b4b4b816-4099-11e7-9465-c2f4403560fa.png)
2. It works so slow(it takes a whole week for two epochs of clean-360 subset)

## Minimum reproducible example
use the default.cfg to train the deep speech model.

## Steps to reproduce
1. python main.py --python main.py --configfile default.cfg

## What have you tried to solve it?

1. Is there any result/performance you have tested in librispeech?

**Comment by piiswrong** [comment]
@Soonhwan-Kwon

**Comment by Soonhwan-Kwon** [comment]
train only on clean-360 can be bad. I'm training on the whole(teain+teain_360+train_5000) dataset and got results cer 0.362836,0.207333,0.173531,0.156486 on epoch 0,1,2,3 for the test-clean and for the train (sample every 100 batch)0.5152, 0.2408,0.1883,0.1622.And it is slow for now because it doesn't use rnn fused cell or variable length approach, but we are working on for the improvement.

**Comment by Soonhwan-Kwon** [comment]
![image](https://cloud.githubusercontent.com/assets/7395166/26518285/7d5f17fc-42e8-11e7-9c39-62b095d3152d.png)

**Comment by Soonhwan-Kwon** [comment]
And there is deepspeech.cfg for real use and default.cfg is for just for the example.

**Comment by xinq2016** [comment]
@Soonhwan-Kwon , @piiswrong 
Many thanks. I will try it again.

**Comment by xinq2016** [comment]
@Soonhwan-Kwon ， after the sorted epoch, the random epochs get no much improvement in my training as shown in the figure. Can you give me some advice, please?
![cer](https://user-images.githubusercontent.com/20516775/27572676-e5ed8ed8-5b3f-11e7-984f-f5fe52263050.png)

**Comment by Soonhwan-Kwon** [comment]
I found baidu's flac to wav script has bug when it has short duration, it generates repeated sound file as  many 6 times or more. So I changed flac to wav converter from avconv to sox, and I found it generates identical outputs but fixes bug. I put fix of fiac_to_wav.sh on https://github.com/samsungsds-rnd/deepspeech.mxnet/commit/ee99375ed5082ec38d03fe0cf30c1c5284edea0c for now. But I am middle of testing because found the bug yesterday with my team member, it may takes time to confirm it doesn't makes any unintended effect on model.

**Comment by Soonhwan-Kwon** [comment]
@xinq2016 I pulled request but it is not permitted yet. Please see https://github.com/samsungsds-rnd/deepspeech.mxnet for now. And there is a bi-graphemes option to deal with label in bi-graphemes, and the last result of 15% accuracy was using that option.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by megaSpoon** [comment]
@Soonhwan-Kwon Could you do me a favor to give me guidance of drawing performance curve like you did?

**Comment by ThomasDelteil** [comment]
@megaSpoon have a look at mxboard https://github.com/awslabs/mxboard
