### ISSUE TITLE
R.I.P. to Antti-Pekka Hynninen

### ISSUE THREAD

**Issue by mli** [apache/incubator-mxnet#6446]
With great sadness, I inform you that Antti-Pekka @ap-hynninen died with his wife in a car accident on last Sunday. 

Antti-Pekka joined us earlier this year. He made a great contribution to MXNet, especially on FP16 supports. He is one of the most talented engineers I have met. It's a great loss to us, his friends and his family. Please join us to memorize him on https://www.plumfund.com/memorial-fund/tram-and-aps-memorial-fund

**Comment by phunterlau** [comment]
R.I.P.

**Comment by ZihengJiang** [comment]
R.I.P.

**Comment by antinucleon** [comment]
R.I.P

**Comment by soumith** [comment]
This is so sad to hear :(

it's incredibly sad to see someone who shared the same spirit, soul and thinking leave the world.

To AP's family - my deepest condolences!

**Comment by pluskid** [comment]
RIP

**Comment by eric-haibin-lin** [comment]
R.I.P.

**Comment by terrychenism** [comment]
R.I.P.

**Comment by bhavinthaker** [comment]
Very sad to hear that. Our heartfelt condolences. R.I.P.

**Comment by kevinthesun** [comment]
R.I.P

**Comment by sandeep-krishnamurthy** [comment]
R.I.P

**Comment by nswamy** [comment]
R.I.P

**Comment by tornadomeet** [comment]
R.I.P

**Comment by sxjscience** [comment]
R.I.P

**Comment by zihaolucky** [comment]
R.I.P.

**Comment by gengyifeng** [comment]
R.I.P

**Comment by javelinjs** [comment]
R.I.P

**Comment by Ldpe2G** [comment]
R.I.P

**Comment by dsqx71** [comment]
R.I.P

**Comment by al-rigazzi** [comment]
R.I.P.

**Comment by zackchase** [comment]
I regret that I never got to know him. RIP

On May 25, 2017 1:16 PM, "Mu Li" <notifications@github.com> wrote:

With great sadness, I inform you that Antti-Pekka @ap-hynninen
<https://github.com/ap-hynninen> died with his wife in a car accident on
last Sunday.

Antti-Pekka joined us earlier this year. He made a great contribution to
MXNet, especially on FP16 supports. He is one of the most talented
engineers I have met. It's a great loss to us, his friends and his family.
Please join us to memorize him on https://www.plumfund.com/
memorial-fund/tram-and-aps-memorial-fund

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dmlc/mxnet/issues/6446>, or mute the thread

**Comment by Godricly** [comment]
R.I.P.

**Comment by Soonhwan-Kwon** [comment]
R.I.P.

**Comment by kindruth** [comment]
R.I.P.

**Comment by thatindiandude** [comment]
Rest in peace

**Comment by MarkWh1te** [comment]
R.I.P.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
