### ISSUE TITLE
[feature req / question ] slurm scheduler support for launch.py? (distrubted processing / multi-machines support)

### ISSUE THREAD

**Issue by moskewcz** [apache/incubator-mxnet#6548]
from reading the docs, it seems like it would be natural to add/have support for the SLURM cluster job scheduler in launch.py (and i guess then also in dmlc_core/dmlc_tracker) -- but before i start working on it:

- does that make sense?
- is it already done and/or somehow not needed?
- is there interest in a PR to add such support if i write it?
- should i post a similar issue in dmlc_core either in-addition-to or instead-of here?
- any other advice/notes?

thanks, mwm.

**Comment by piiswrong** [comment]
More platform support is always better. I haven't heard of anyone working on this. You are welcome to PR.

**Comment by al-rigazzi** [comment]
Hi @moskewcz, can I ask you the status of this?

**Comment by herryz** [comment]
Hi, @moskewcz , I have used slurm to run distributed mxnet job in v0.9.5, but in v 0.10.0, when I run distributed mxnet job with gpu resources, it meet some questions.

e.g. I run a job in 2 nodes, and I have 1 gpu on each node. when I use "srun" to launch 1 root ,2 server ,2 worker, and of course the 2 worker progress will use gpu resources. So ,the question is the root and server progresses have no gpu resources, it report a error.

Do you have any solutions of this. thx a lot

**Comment by moskewcz** [comment]
hi all --

i'm not actively working on this, but it's still on my backlog and i'm still interested in it. for now, we're currently mostly okay with single-node (multi-gpu) training, using slurm to manage a moderate number of nodes/users, so distributed mxnet training+slurm isn't critical yet. i did some initial experiments using launch.py (ssh mode) + measure.py, and wasn't able to get that to work correctly / reliably, so i figure i'm not ready to approach the slurm integration side of things yet (although perhaps actual training works better than measure.py?).

after wading though various issues with the pslite build process and code (i.e. it downloads and static links it's own libprotobuf, making the resulting mxnet build incompatible with an app that uses some other protobuf version), i concluded that (IMO) there were too many levels of complexity involved in the mxnet distributed flow: too many repos, too many processes (root + servers + workers; i'd prefer just root + workers, or maybe just workers (mpi-style)), too much dead/experimental/oddly-shared code (e.g. rabit), unused modes, hard to trace call stacks (on startup, how does each process determine what it's job it, and what control flow path does it follow?), and so on, so that also didn't make me super-eager to dive into it in too much depth just yet. i assume many (some?) people do use distributed mode, and that maybe that number will increase over time. i'm somewhat hoping perhaps more documentation/stability/simplicity might materialize if i wait ... or there's always tensorflow in the google cloud ;)

**Comment by al-rigazzi** [comment]
Hi everyone, I created a basic SLURM launch module, and [issued a PR for it](https://github.com/dmlc/dmlc-core/pull/288). 

It is simple and tested on different Cray systems using native SLURM (salloc+srun or sbatch+srun). You can have a look at it and tell me what you would like to see supported.

@herryz do I understand correctly, that you'd like to use GPUs only for workers and not for servers and root?

**Comment by herryz** [comment]
@al-rigazzi yep, you understand correctly, but in my case every node has 1 server and 1 worker progress, and the master node also have 1 root progress. 

And.. sorry I'm a little confused. In your solution, do you mean I have to use launch.py to start my job? 
like add  'python ../../tools/launch.py -n 2 -H hosts  --launcher=slurm python train_cifar10.py'   into my slurm jobfile? 

in my case, I first request resources in jobfile, like 2 nodes and 2 gpus on each node, then I consume them in 5 srun (1 root, 2 servers ,2 workers), use
root:  'srun -N 1 -n 1 -gres=gpu:0 --nodelist=node1 -l python ...'
server: 'srun -N 1 -n 1 -gres=gpu:0 --nodelist=node1 -l python ...'  
worker:'srun -N 1 -n 1 -gres=gpu:1 --nodelist=node1 -l python ...'
server: 'srun -N 1 -n 1 -gres=gpu:0 --nodelist=node2 -l python ...'  
worker:'srun -N 1 -n 1 -gres=gpu:1 --nodelist=node2 -l python ...'  
then the root and server 'srun' will meet an error that they cannot find gpus resource(because of I use 'context=mx.gpu() ' in my code).

and of course I add the env before each 'srun'.
so, do you have any idea?

**Comment by al-rigazzi** [comment]
Hi, yes, indeed the module has to be used for launch.py (even though I could not apply the changes to it, since it is in the MXNet repo).

Concerning the GPUs, yes, that is a known problem (to me). Launcher simply launches the same command line on servers and workers, and (if I remember correctly) if you don't specify --gpus=none, it looks for gpus. But if you specify it, then you will have no GPU on workers too.

So, in my opinion, you could modify the launcher (like slurm.py) to include the --gpus=none only for servers, but I can not guarantee it will work.

**Comment by herryz** [comment]
@al-rigazzi 
That didn't work.  I found slurm can specify"--gres=gpu_mem" to share a gpu resource with multiple jobs. But it meet an error in my env.
"salloc: error: Job submit/allocate failed: Requested node configuration is not available"

maybe this way may work(share a resource with multiple jobs).

**Comment by al-rigazzi** [comment]
That might work, yes.
Many problems can arise from how SLURM is set, anyhow. E.g. you should also be sure that SLURM is set to allow node sharing (that's why I put --exclusive=user). But maybe this questions could also be asked to the SLURM developers, who might have more experience.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
