### ISSUE TITLE
some problems of mx.nd.Convolution() ....

### ISSUE THREAD

**Issue by kobenaxie** [apache/incubator-mxnet#6763]
**NO.1**
According :https://github.com/dmlc/mxnet/pull/5096 
I try to test 3D-convolution, but why the result are all zeros ?

import mxnet as mx

def test_Convolution3D(conv3D):
    data = mx.nd.arange(24).reshape((2,1,2,2,3))
    conv3D_ex = conv3D.simple_bind(mx.cpu(), arg_dicts={'data':data})
    conv3D_ex.forward()
    return conv3D_ex.outputs[0].asnumpy()

x = mx.sym.Variable('data', shape=(2,1,2,2,3))
conv3D = mx.sym.Convolution(data=x, kernel=(2, 2, 3), pad=(1, 1, 1), num_filter=2)

print test_Convolution3D(conv3D)

**NO.2**
and another question:

import mxnet as mx
a = mx.nd.arange(24).reshape((2,1,2,2,3))
b = mx.nd.Convolution(data=a, kernel=(2, 2, 3), no_bias=True, pad=(1, 1, 1), num_filter=2)
print b.asnumpy()

Error  message:
MXNetError: [22:39:32] src/c_api/c_api_ndarray.cc:55: Check failed: num_inputs == infered_num_inputs (1 vs. 2) Expecting 2 inputs, got 1 in operator Convolution

**Comment by reminisce** [comment]
No. 1
You used simple_bind, so all the ndarrays are initialized in backend as zeros. You can initialize those ndarrays before calling forward using the `arg_dict` interface of the executor `conv3D_ex`.

No. 2
Convolution takes two arguments when bias is off, `data` and `weight`. In order to use the imperative interface, you need to provide both. Consider the following:
```python
import mxnet as mx
a = mx.nd.arange(24).reshape((2,1,2,2,3))
weight = mx.nd.ones((2, 1, 2, 2, 3))
b = mx.nd.Convolution(data=a, weight=weight, kernel=(2, 2, 3), no_bias=True, pad=(1, 1, 1), num_filter=2)
print b.asnumpy()
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
