### ISSUE TITLE
should add row_sparse_push for kvstore

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#7569]
hi, all, @eric-haibin-lin 
I noticed that you have add a function for kvstore , named 'row_sparse_pull', why not to add a 'row_sparse_push'. it is very like my 'partial weight' which is in https://github.com/starimpact/mxnet_v0.8.0/blob/b8ba5a9c8b6d6b7876716a37fbc9284ecf55b920/python/mxnet/kvstore.py#L241
my partial weights can support distribution training.

**Comment by eric-haibin-lin** [comment]
The push method accepts row_sparse values already, but for pull it requires row id that's why row_sparse_pull was added. 

On 2017年8月22日, at 19:40, Zhang Ming <notifications@github.com> wrote:

hi, all,
I noticed that you have add a function for kvstore , named 'row_sparse_pull', why not to add a 'row_sparse_push'. it is very like my 'partial weight' which is in https://github.com/starimpact/mxnet_v0.8.0/blob/b8ba5a9c8b6d6b7876716a37fbc9284ecf55b920/python/mxnet/kvstore.py#L241
my partial weights can support distribution training.

**Comment by starimpact** [comment]
Can not find where is the push() method which can support row_sparse in kvstore.py. where is it?

**Comment by eric-haibin-lin** [comment]
Thanks for pointing that out. The documentation for push() doesn't contain any example for rowsparse yet. The logics for rowsparse push is in the cpp backend https://github.com/apache/incubator-mxnet/blob/master/src/kvstore/kvstore_dist.h#L314 
I'll update the documentation in the next PR.

**Comment by eric-haibin-lin** [comment]
Doc has been updated. closing this issue for now

**Comment by starimpact** [comment]
where is it?

**Comment by eric-haibin-lin** [comment]
https://mxnet.incubator.apache.org/versions/master/api/python/kvstore/kvstore.html#mxnet.kvstore.KVStore.row_sparse_pull
and 
https://mxnet.incubator.apache.org/versions/master/api/python/kvstore/kvstore.html#mxnet.kvstore.KVStore.push
