### ISSUE TITLE
MXNet 0.11.0 Release Feedback: Source Headers and License Files

### ISSUE THREAD

**Issue by mbaijal** [apache/incubator-mxnet#7749]
As discussed in various email threads - [Voting thread](https://lists.apache.org/thread.html/171c0ff73e5f7539611a8024fef42968f5ffea800c354b2cdfa04ab2@%3Cgeneral.incubator.apache.org%3E), [Source Headers](https://lists.apache.org/thread.html/78b01bc01e107300257ca2bc7ad04c7eae8c87bcc4cffaaf829813bd@%3Cgeneral.incubator.apache.org%3E) and [ICLAs vs Contributors](https://lists.apache.org/thread.html/d88544cc13275c502a1580b16b0575f9d827a0041c0bd2879b7a9197@%3Cdev.mxnet.apache.org%3E)

**1. Headers**
a) "The source headers should be reverted in any areas where not all contributors to that file have signed ICLAs, otherwise we need some kind of agreement they are OK with moving to NOTICE file (which is how this has been handled in the past)"
b) While a number of file (around 50 odd) do have "Copyright (c) 2016 by Contributors” they don’t have a full Apache licensed header please fix this in the next release. More files exist with other years and without the correct header.

**2. License Files**
a) Missing - BSD license for this file [4]
b) Missing - MIT licensed JQuery and Sizzle.js [5]
c) Missing - This BSD licensed file [6]
d) Missing - Boost Software licensed file [7]
e) Missing - This BSD licensed files [8][9]
f) This license file may be a little misleading [1] where its apache license but also claims “All rights reserved”. I notice this in a number of other places as well.
g) A number of Apache licenses have incorrect appendixes with the copyright line filled in e.g. [2]
h) This file may incorrect have an ASF header on it [3]

**3. Files referred above can be found as follows** - 

[1] ./src/operator/contrib/ctc_include/LICENSE
[2]../dlpack/LICENSE
[3] ./example/image-classification/predict-cpp/image-classification-predict.cc
[4] ./docs/_static/searchtools_custom.js
[5] ./docs/_static/jquery-1.11.1.js
[6] ./cub/test/mersenne.h
[7] ./cmake/Modules/FindJeMalloc.cmake
[8] ./dmlc-core/cmake/Modules/FindCrypto.cmake
[9] ./nnvm/dmlc-core/cmake/Modules/FindCrypto.cmake

**Comment by szha** [comment]
Why are we hosting our own jquery? They have their own CDN and has a minified version instead of the full version, which is good for loading time.

**Comment by mbaijal** [comment]
Questions - 
1. It says that the LICENSE of files like - /dlpack/LICENSE, ./cub/test/mersenne.h should be corrected (they include copyrights). Can I correct these submodule licenses ?

2. There were several email threads in this regard - “The source headers should be reverted in any areas where not all contributors to that file have signed ICLAs, otherwise we need some kind of agreement they are OK with moving to NOTICE file (which is how this has been handled in the past)“. Have we decided on how to handle this?

3. Is this file actually supposed to have the Apache license: https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc?

**Comment by hen** [comment]
My thoughts on this, all of which should be fixed for the next release:

1. Headers:

Any file that existed before the dmlc->apache move should have two headers. The old one and the standard ASF one. Any file that was created after the code move should have only the standard ASF header. Note that this is high level, there may be a file that has other types of src headers, like maybe a piece of BSD code was copied in etc. 

2. License files. All these should be fixed. 

--

On your questions:

1: I don't think we should be changing those two files. The files are currently in dmlc and not in apache. They are a style-bug in dmlc, and we do have the question of whether we should be pulling this code into mxnet as source the way we do.

2: I believe this means putting back "* Copyright (c) 2015 by Contributors" (or sometimes a different year), wherever that was deleted in https://github.com/apache/incubator-mxnet/pull/7379

3: It does look confusing. It looks like it came in on this pull request pre-Apache days: https://github.com/apache/incubator-mxnet/pull/891 . As it was a contribution to an Apache 2.0 licensed project, the contribution would be under Apache 2.0. It looks like it is a specific version of the DMLC "Copyright Contributors" that is listing the 3 contributors who worked on the pull request. I would treat it the same as you do other DMLC files that say Copyright, but in this case list the three people instead of 'Contributors'.

**Comment by mbaijal** [comment]
Henri, Thanks for your response. 

1. Headers: **both a) and b) are going to affect almost all headers - this is too large a change to include in 0.12.0**.  
This refers to both the points - 
a.  Any file that existed before the dmlc->apache move should have two headers. The old one and the standard ASF one. Any file that was created after the code move should have only the standard ASF header. Note that this is high level, there may be a file that has other types of src headers, like maybe a piece of BSD code was copied in etc.
b.  I believe this means putting back "* Copyright (c) 2015 by Contributors" (or sometimes a different year), wherever that was deleted in #7379

2. License files. All these should be fixed. --**- done**
a) done
b) done
c) submodules - not done
d) done
e) submodules - not done
f) done / submodules- not done
g) done /submodules -not done
h) done - Henri in #3 verified this file should have the ASF header

**Comment by mbaijal** [comment]
@bhavinthaker @srochel 
Do you agree?

**Comment by srochel** [comment]
Henri - #1 is too big a change to take into 0.12 in the last minute. We will address and include in next release.

**Comment by hen** [comment]
Let's flag it in the release vote and see what dev@ and general@incubator say. Release dates are not set in stone.

**Comment by mbaijal** [comment]
All issues here have been fixed.

**Comment by mbaijal** [comment]
This issue was fixed for the 1.0.0 release. New comments are being tracked in a different issue - https://github.com/apache/incubator-mxnet/issues/8913
