### ISSUE TITLE
How to use cpu kernel of an operator (which provides only cpu implementation) in gpu context?

### ISSUE THREAD

**Issue by x10000year** [apache/incubator-mxnet#7759]
If a custom operator (written in c++) only provides cpu implementation, can it be used in gpu context where all other operators have gpu kernel? In Caffe this is straightforward, because when you call Blob's cpu_data() and mutable_cpu_data() it automatically syncs with gpu data.

Thank you.

**Comment by reminisce** [comment]
How are the operator's forward and backward kernels implemented? By kernel, I mean the function block that does parallel computation such as [this](https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/control_flow_op.h#L43). In MXNet, most of the simple operators shares the same kernels between CPU and GPU. That's why there is a template argument called `xpu` in Forward and Backward function as [this](https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/control_flow_op.h#L154). If your cpu kernel also works for gpu and you defined Forward and Backward functions using `xpu` template argument, what you need to do is register the operator in a `.cu` file as [this](https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/control_flow_op.cu#L29).

Sometimes, complicated operators do not share the same kernels for cpu and gpu as they have different parallelization approaches and each kernel has to be optimized against its own device.

**Comment by x10000year** [comment]
@reminisce The cpu kernel is a complex algorithm that needs direct access to the raw cpu memory. Only cpu kernel is provided and I intend to use the cpu kernel in gpu context (like caffe, which uses cpu kernel when no gpu kernel is provided, and cpu_data() can automatically sync with gpu data).

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
