### ISSUE TITLE
Low accuracy of pvanet

### ISSUE THREAD

**Issue by qingzhouzhen** [apache/incubator-mxnet#7820]
I have changed a model which called pvanet from caffe [https://github.com/sanghoon/pva-faster-rcnn](https://github.com/sanghoon/pva-faster-rcnn), it is a implementation of the article by the author [https://arxiv.org/abs/1608.08021](https://arxiv.org/abs/1608.08021), my problem is why my accuracy is low than author's
What I have done:
1 Implement the classification net: [https://github.com/qingzhouzhen/incubator-mxnet/blob/pvanet-e2e/example/image-classification/symbols/pvanet.py](https://github.com/qingzhouzhen/incubator-mxnet/blob/pvanet-e2e/example/image-classification/symbols/pvanet.py)
2 feed the classification to Faster R-CNN module: [https://github.com/qingzhouzhen/incubator-mxnet/blob/pvanet-e2e/example/rcnn/rcnn/symbol/symbol_pvanet.py](https://github.com/qingzhouzhen/incubator-mxnet/blob/pvanet-e2e/example/rcnn/rcnn/symbol/symbol_pvanet.py)
Most job I have done is to atapt Faster-R-CNN,  replace the vgg pre-trained model with pvanet pre-trained model, for details see #7786 
Firstly the classification net pvanet's accuracy is 64.0%(70.6% as article)
Secondly detection net (pvanet+rpn+rcnn)'s mAP is 59.37%(82.5% as article)
I checked my net structure carefully to make it the same as author's implementation in caffe, is there anything I do wrong?

**Comment by chinakook** [comment]
1. You can fix the same net weights in both caffe and mxnet, and debug layer by layer to see the result is whether the same.
2. Check mean file and std scale value.
3. Weights initialized with mx.random.normal in mxnet is worse than Xaviar or msra. So weights initialization is very sensitive in mxnet, otherwise you will get bad result as my experience.
4. I can't understand the meaning of the line 'pool5 = mx.sym.Pooling(data=bsr, kernel=(1, 1), stride=(1, 1), pad=(0, 0), pool_type='max', name='pool5')'. Moreover, pooling is 'valid' in mxnet but 'full' in caffe.
Anyway, If you want to port caffe to mxnet, fix the same net weights and compare the result of inferencing result of both framework is needed. As for training, It's complicated because the platform differences.

**Comment by qingzhouzhen** [comment]
Thanks for such a detailed answer @chinakook

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
