### ISSUE TITLE
label_width doesn't work as expected

### ISSUE THREAD

**Issue by hikingman30** [apache/incubator-mxnet#7906]
I made all images with <256 boxes, but label_width = 350 still not work and suggests me to set over 1500, would like to know if this needs to be considered with batch size as well, or GPU number
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:
0.11
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by szha** [comment]
Others will have a hard time to help you because of lack of information on 1. what your usage/code looks like and what interfaces you're using, 2. what your environment looks like, os, mxnet version, etc. The issue template serves the purpose of helping you communicate the problem effectively, so please fill those in.
