### ISSUE TITLE
mxnet_predict.so read the symbol json error

### ISSUE THREAD

**Issue by novioleo** [apache/incubator-mxnet#7908]
## Environment info
Operating System:
Ubuntu 16.04
Compiler:
arm-linux-androideabi-clang++ (arch = arm,api=21)

i met a problem when i tried to use the latest mxnet_predcit.so in android.
the latest predict.so can not load the symbol rightly.

> 

i upload my predict.so and the model json in my attachments.

[symbol.json.zip](https://github.com/apache/incubator-mxnet/files/1305754/symbol.json.zip)
the mxnet_predict.so can not upload successfully,so i upload to BaiduYun:
https://pan.baidu.com/s/1kVGFkDT

any help is appreciate

**Comment by novioleo** [comment]
is there any one meet this error?

**Comment by szha** [comment]
@arank

**Comment by novioleo** [comment]
@szha these is no response.....
i'll try to rewrite my program as a independent shared object in c++ with mxnet only as a last resort.

**Comment by arank** [comment]
Currently we don't have official cross compile instructions for Raspberry Pi, and we support building the .so natively on the Pi with Raspbian. Could you try that? Otherwise you can try these cross compile steps for ARM from our old arm build test dockerfile, however I'm not sure if this process will work to build the .so for the Pi https://github.com/apache/incubator-mxnet/blob/master/tests/ci_build/Dockerfile.crosstool

**Comment by novioleo** [comment]
@arank tks for your reply,i think it can't solve my problem,i'd like to invoke the naive c++ interface.

**Comment by arank** [comment]
Thanks for clarifying the purpose here @novioleo. We currently don't have a super well documented process for the C++ api, but one you have the correct .so against the Pi system you can look at this issue and see if the C++ process referenced there helps, https://github.com/apache/incubator-mxnet/issues/868

**Comment by novioleo** [comment]
@arank ok,very pleasure to help.
