### ISSUE TITLE
Be respectful to other people. (original title: well, I have solved this issue but the crude contributor locked the issue)

### ISSUE THREAD

**Issue by janelu9** [apache/incubator-mxnet#8093]
#8065

**Comment by janelu9** [comment]
be using a BucketingModule to define your symbol model when you use your custom BucketIter

**Comment by szha** [comment]
All necessary information for resolving your issue has been provided to you in the above thread, and BucketingModule has been repeatedly mentioned in the above locked thread.

I closed the above issue because you're asking others to debug your code, while not being willing to look at API doc. This is disrespectful to other people's time.

I locked the conversation because you were disrespectful to me who helped you on this issue.

I think this kind of behavior is harmful to the community and must be discouraged. I assure you that the same treatment will be applied if such behavior persists.
