### ISSUE TITLE
None type for mx.sym.slice

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#8153]
The op `slice_axis` now supports: `mx.sym.slice_axis(begin=1, end=None, axis=1)`, but this fails: `mx.sym.slice(begin=(1), end=(None))`. Are there any plans for supporting this? Its very useful, as you usually don't want to slice the batch dim, and you also want to be able to change the batch size without having to create a new symbol.

@sxjscience

**Comment by taliesinb** [comment]
Given that `slice$axis` supports negative indices, you should just be able to specify `begin=0, end=-1` and that'll do what you want.

But that by the way is a no-op: because `slice_axis` targets one axis at a time, if you want to write batch-neutral ops, you would just never do a `slice_axis` on level 0 in the first place. 

So were you thinking about `slice`? Because that _does_ force you to specify a slice to apply to the batch dimension. But again, `slice` supports negative indices too. So as far as I can see we can close this issue.

**Comment by taliesinb** [comment]
So @sbodenstein pointed out to me offline that numpy-style negative indices don't allow you to specify the very end, inclusive. Indeed we need then to allow None as a spec. And I see his comment is about adding this feature to `slice` rather than `slice_axis`, I simply misread the original comment.

**Comment by sbodenstein** [comment]
@szha, @sxjscience: we would really like to plan a way forward on this issue, as its preventing us using `slice` for Mathematica (we create batch-size independent execution plans). We can also implement the solution if needed.

**Comment by szha** [comment]
I agree that this should be useful. The sparse version will need to be changed along with the dense version. cc @eric-haibin-lin in case there would be any complication.

Would either of you like to give it a go?

**Comment by sbodenstein** [comment]
Ok, will have time next week.

**Comment by eric-haibin-lin** [comment]
It should be supported already. Feel free to reopen if it's not working
