### ISSUE TITLE
Implementing a new activation function in Gluon

### ISSUE THREAD

**Issue by anjishnu** [apache/incubator-mxnet#8422]
Hi, if we wanted to swap out activation functions to try things with the new Gluon API, what would be the best way to do so? If the results are good we would also want to contribute them back to MxNet.

**Comment by anjishnu** [comment]
To be more precise - if we compare PyTorch and MxNet Gluon, https://mxnet.incubator.apache.org/api/python/gluon.html#mxnet.gluon.nn.Activation
 it seems like we should be fine if we could implement some (for e.g. Python code) that adheres to this API and replace it in an existing model, but it seems that the block API currently doesn't accept any custom 'Activation' objects, only a string representation which is passed to the underlying C++ Activation implementation. 

Would it be useful to create APIs for easily passing Activation object subclasses to easily out and try out new without needing to rewrite full models? A contrib folder for Gluon could contain all the activations that do not have an efficient C++ implementation yet.

This seems relevant given that there have been solid incremental improvements in this area:
ELUs : https://arxiv.org/abs/1511.07289
SELUs: https://arxiv.org/abs/1706.02515
Swish : https://arxiv.org/abs/1710.05941

**Comment by mseeger** [comment]
Can you express your new activation in mx.nd primitives? If so, just use no activation in the linear, and concatenate with your code for the nonlinearity. You have to write this in mx.nd in order to be efficient.

If you need a new nonlinearity, not included in mx.nd, you'd have to extend MXNet, in particular src/operator/mshadow_op.h, and also register a new operator. This is a bit tricky, but you can ask me, I just did it.

But please do make sure you cannot express your function with existing ones: a lot of things are perfectly possible with mx.nd.

**Comment by anjishnu** [comment]
Thanks Mathias, I think that what I have in mind is quite simple so it should be implementable with mx.nd.

**Comment by anjishnu** [comment]
Would it make sense if I contributed any activation functions I implement as Gluon blocks, for instance?

**Comment by mseeger** [comment]
Hello,
if the missing activation functions are frequently used, it would be most useful to extend the Activation operator. This has to be done in C++, but is not all that hard. If you want to give it a try, I can review it.

Otherwise, why not implement something in Python, say a new Gluon Block, and commit it an as example to MXNet? Thereby, people can use it, if you document it well enough with examples.

**Comment by anjishnu** [comment]
That's a good idea mathias. I submitted a PR here.

https://github.com/apache/incubator-mxnet/pull/9111/commits/c56fe91f0c319f709b39a5ca7001289a939c2b64

**Comment by cjolivier01** [comment]
This appears to be resolved in this merge: https://github.com/apache/incubator-mxnet/pull/9662
Please reopen if necessary

**Comment by cjolivier01** [comment]
This appears to be resolved in this merge: #9662
Please reopen if necessary
