### ISSUE TITLE
does libsvm data ought to be  sorted in ascending order for every row?

### ISSUE THREAD

**Issue by liumilan** [apache/incubator-mxnet#8481]
If not ascending order,does will it have a wrong result during trainning?
Can it possible to support random order for every row?
@eric-haibin-lin

**Comment by formath** [comment]
As I know, there is no order in data extracted from dmlc-core libsvm dataiter. So, it should has no order in SparseNDArray in mxnet too. During training, the order does not matter for SparseNDArray.

**Comment by liumilan** [comment]
i just get it from comment in iter_svm.cc code
The input data is stored in a format similar to LibSVM file format, except that the **indices
are expected to be zero-based instead of one-based, and the column indices for each row are
expected to be sorted in ascending order**.
@formath

**Comment by formath** [comment]
Update:
The id index in RowSparseNDArray is sorted in ascending order. This order is used in pull&push for encoding the key.

**Comment by eric-haibin-lin** [comment]
Yes it expects sorted order per row for indices. Otherwise the CSRNDArray is invalid, leading to calculation error. 
If you dataset is not sorted, you can first convert CSRNDArray to scipy and back to CSRNDArray, which always give you a valid CSRNDArray (after https://github.com/apache/incubator-mxnet/pull/8362 is merged). 
e.g. 
```
batch.data[0] = sparse.csr_matrix(batch.data[0].asscipy())
```

For rowsparse the indices is also expected to be sorted. We're also adding a format checker in https://github.com/apache/incubator-mxnet/pull/8259 

Closing this for now. We're moving Q&A questions to https://discuss.mxnet.io/ Feel free to ask follow-up questions on the forum :)
