### ISSUE TITLE
Problem in mx.io.ImageRecordIter

### ISSUE THREAD

**Issue by jongchyisu** [apache/incubator-mxnet#8552]
Hi, 
I have found a potential bug in the ImageRecordIter. I found that even after reset, I can still get StopIteration. I need to do the reset twice (which doesn't make sense) to avoid exception. I also followed the way to use ImageRecordIter in the fit function in module.py, but I found the number of batches I can get is different in each epoch. 

Here is a simple code that you can reproduce the error:

```
import mxnet as mx
from mxnet.io import DataBatch, DataIter
import numpy as np

batch_size = 64
num_images = 5794 # number of images here
train_data = mx.io.ImageRecordIter(
        path_imglist = , # list file path here
        path_imgrec = , # rec file path here
        data_shape = (3, 256, 256),
        batch_size = batch_size)

num_batches = np.ceil((num_images)*1.0/batch_size).astype(np.int)

for epoch in range(10):
    print(epoch)
    # train_data.reset() # need to reset twice here to avoid exception
    for i in xrange(num_batches):
        data_batch = train_data.next()
    train_data.reset()
```

Here is another simple code to reproduce the issue of different number of batches in each epoch:
```
for epoch in range(10):
    print(epoch)
    data_iter = iter(train_data)
    end_of_batch = False
    counter = 0
    next_data_batch = next(data_iter)
    while not end_of_batch:
        counter += 1
        data_batch = next_data_batch
        try:
            # pre fetch next batch
            next_data_batch = next(data_iter)
            # self.prepare(next_data_batch)
        except StopIteration:
            end_of_batch = True
    print(counter)
    train_data.reset()
```

Seems like this problem is due to the number of images cannot be divided by the batch size. But even though the reset function is not working properly.

**Comment by ptrendx** [comment]
The variable number of batches per epoch is kind of intentional. What happens here is basically: if the number of images is not divisible by the batch size, then iterator needs to fill the last batch with something after it used all of the images. By default it uses images from the next epoch (you can change that behavior by setting `round_batch` option of the iterator to `False`). Then, during the next epoch, it does not use those images (otherwise those images would be overrepresented in the training process), which in some cases may result in that epoch having 1 less batch.

**Comment by jongchyisu** [comment]
I see, but why do I need to reset twice to avoid exception error?

**Comment by ptrendx** [comment]
`reset` function used here has 2 slightly different behaviors due to that feature of the iterator - the first time you call it iterator knows it hit the end of epoch and internally already reset itself (to get those overflow images from the next epoch) and does not do anything else (besides setting its internal end of epoch indicator to `false`) - this means that this epoch will not include those overflow images. When you call it the second time iterator is in the middle of epoch and so resets itself completely - this makes the epoch give you all of the images, including those that were used at the end of the previous epoch.

As I said, if you would prefer different behavior (not taking images from the next epoch and so having each epoch have the same number of images, you can use the `round_batch = False` option of the iterator).

**Comment by jongchyisu** [comment]
I see, thanks for the explanation!

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.
