### ISSUE TITLE
How to use Prelu in gluon?

### ISSUE THREAD

**Issue by HaoLiuHust** [apache/incubator-mxnet#8559]
I see a layer called Prelu in caffe and pytorch, is it include in mxnet, especially in gluon interface?

**Comment by HaoLiuHust** [comment]
found the solution

**Comment by ShownX** [comment]
How?

**Comment by HaoLiuHust** [comment]
@ShownX gluon.nn.LeakyReLU

**Comment by ShownX** [comment]
LeakyReLU != PReLU

**Comment by HaoLiuHust** [comment]
@ShownX I think their definition are same, you can refer pytorch

**Comment by HaoLiuHust** [comment]
Maybe I have make the mistake

**Comment by bradcar** [comment]
yes leaky ReLU isn't parameterized leaky relu.

I would love to see a PLReLU in Gluon.

All of this is made a bit more confusing since in MXNet, the mxnet.symbol.LeakyReLU
https://mxnet.incubator.apache.org/api/python/symbol.html#mxnet.symbol.LeakyReLU
takes a parameter act_type that can take on the implement several differet types of activation functuobs... ({'elu', 'leaky', 'prelu', 'rrelu'},optional, default='leaky').

    elu: Exponential Linear Unit. y = x > 0 ? x : slope * (exp(x)-1)
    leaky: Leaky ReLU. y = x > 0 ? x : slope * x
    prelu: Parametric ReLU. This is same as leaky except that slope is learnt during training.
    rrelu: Randomized ReLU. same as leaky but the slope is uniformly and randomly chosen from [lower_bound, upper_bound) for training, while fixed to be (lower_bound+upper_bound)/2 for inference.
