### ISSUE TITLE
How many new data points does data augmentation with mx.io.ImageRecordIter produce?

### ISSUE THREAD

**Issue by MennoK** [apache/incubator-mxnet#8600]
I think I have an understanding of the concept of data augmentation (basically you increase the dataset by transforming the given data images). I understand you can call data augmentation with mx.io.ImageRecordIter by specifying certain parameters, e.g. cropping or rotation.

However, how many 'new' data images do ImageRecordIter generate and where do you specify it? For example, does it generate just one random rotation for the training given image, or does it produce multiple rotations of the same image, say 10 rotations between +20 and -20 degrees and use the 10 'new' images to train a model?

**Comment by ptrendx** [comment]
Augmentations do not increase the size of your dataset explicitly. How it works is that every time an iterator sees a particular image (so once every epoch) it augments it producing 1 output (so every epoch you will see slightly different image).

**Comment by MennoK** [comment]
Thanks for answering. 

Is it wrong to increase your training data explicitly by providing for example the original image and a flipped version of the image. Would this help to learn a model better?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by bhavinthaker** [comment]
It may not be wrong to augment an existing dataset with flipped version of the image.

Few links on Data augmentation:
1. https://www.coursera.org/learn/convolutional-neural-networks/lecture/AYzbX/data-augmentation
2. http://cs231n.stanford.edu/reports/2017/pdfs/300.pdf

Please label: question, how-to

I would suggest closing this issue since the question is answered. See szha's guidance above on further questions/discussions.
