### ISSUE TITLE
5 Different issues created for the same problem and yet no solution

### ISSUE THREAD

**Issue by SrivastavaKshitij** [apache/incubator-mxnet#8853]
Hi There 

I am facing a problem with mxnet.mod.module API where I try to run my code and the code throws an error which is:

`ValueError: Data provided by data_shapes don't match names specified by data_names ((DataDesc[_0_data,(16,) vs ['data'])` 

Now there are 5 different issues created for the same problem such as:

[Issue 7681](https://github.com/apache/incubator-mxnet/issues/7681)
[Issue 7422](https://github.com/apache/incubator-mxnet/issues/7422)
[Issue 6801](https://github.com/apache/incubator-mxnet/issues/6801)
[Issue 6301](https://github.com/apache/incubator-mxnet/issues/6301)
[Issue 8339](https://github.com/apache/incubator-mxnet/issues/8339)

Some of them are open and others have been closed by contributors for the lack of activity. I dont understand why are you guys closing the issue without a concrete solution. You do realize that you are not actually "contributing" anything by closing the issue midway without a solution.

I would like somebody to help with this problem

Thanks

**Comment by szha** [comment]
Hi @SrivastavaKshitij. I checked the above five listed issues and they all come from different usage (i.e. different code), so I think it's premature to claim them to be the "same problem". Thus, I don't think an issue that aggregates them would be logical or helpful. If you have evidence to support such claim, please do share. Otherwise, if you have specific error that you need help with, please follow the issue template and provide necessary information. Thank you for your cooperation.

**Comment by piiswrong** [comment]
This is an exception the tells you you are using the API incorrectly.

You need to fix your code, but other people can't help you with that if you don't post any useful information like your code and data.

See this nice post explaining how to ask a question: http://www.catb.org/esr/faqs/smart-questions.html

**Comment by aaronmarkham** [comment]
#9460 should have fixed this.

**Comment by SuperLinguini** [comment]
Proposed Labels: "Python", "Bug", "Module",
