### ISSUE TITLE
mx.io.NDArrayIter with scipy.sparse, last batch becomes dense and with no warning upfront

### ISSUE THREAD

**Issue by dingran** [apache/incubator-mxnet#9211]
I noticed that mx.io.NDArrayIter accepts scipy sparse matrix but does not properly handle the last batch (it becomes dense) and did not output an error/warning upfront (like it would do with nd.sparse matrix, with a message "`NDArrayIter` only supports ``CSRNDArray`` with `last_batch_handle` set to `discard`.").

Please see attached ipython notebook printout as an example.
printout: [example.pdf](https://github.com/apache/incubator-mxnet/files/1589726/example.pdf)
ipynb file: [example.zip](https://github.com/apache/incubator-mxnet/files/1589725/example.zip)

Mixing dense with sparse is not too bad with imperative mode but throws off the computation in symbolic mode (i.e. hybridized blocks) and the error messages weren't very helpful.
![2017-12-27_14-40-20](https://user-images.githubusercontent.com/12864782/34391493-f8f59188-eb13-11e7-9865-d89dd1c4316b.jpg)

**Suggest to let NDArrayIter have the same behavior for scipy.sparse and nd.sparse.**

**Comment by eric-haibin-lin** [comment]
Thanks for reporting this. 
Supporting `last_batch_handle ` options other than `discard` with sparse matrix is on the TODO list. We'll support it after MKL concat operator is merged so that it properly returns a sparse matrix. For now probably we should add the missing error message 
@ZiyueHuang

**Comment by ZiyueHuang** [comment]
Sure. Working on it.

**Comment by dingran** [comment]
Hi @eric-haibin-lin, by the way, I have a related observation regarding sparse. It seems as though the operator is slower (less optimized?) compared to handling dense matrix, at least on GPU. 

I don't have a simple example readily available, but you can take a look here https://github.com/dingran/nvdm-mxnet/blob/master/nvdm.ipynb

In cell [3], the flag `use_dense` controls whether to use sparse or dense matrix. Even counting the cost of converting mini batches of CSR into dense, the training speed when using dense matrix is still about 15~20% faster for this particular example. 

Would be good to have some benchmark between CSR and dense operators on CPU and GPU as guidelines (do we have them somewhere?) Thanks!

**Comment by eric-haibin-lin** [comment]
@dingran I’ll take a look at your notebook shortly

**Comment by eric-haibin-lin** [comment]
Hi @dingran 
I just noticed that you're using gluon interface with sparse ndarray. Unfortunately this is not supported yet. The gluon interface will try to run all operators with dense data/weight/gradient if you hybridize it. You probably will observe storage fallback messages in your console/terminal. 

If you don't hybridize the network, you can probably run it in imperative mode (I haven't verify it personally, so there's no guarantee that it works without any conversion between sparse and dense ndarrays..). Note that the `nn.Dense` layer uses `FullyConnected` operator, which doesn't support csr inputs (due to legacy operator interface that doesn't support sparse, we're fixing it). So it's actually converting everything into dense to perform the operation. Instead you can create a custom layer with sparse.dot operator which supports csr input to replace `nn.Dense` (note that the weight is transposed in FC though). 

Gluon sparse support is on the roadmap. Currently the easiest way to use the sparse feature is still through the symbol interface (unfortunately)

**Comment by dingran** [comment]
I see, thanks for explanation!
