### ISSUE TITLE
"bad" mAP score on COCO

### ISSUE THREAD

**Issue by qxin** [apache/incubator-mxnet#9275]
Hi, sorry... but I trained coco using this mxnet SSD, and i found that the mAP ( iou:[0.5]) is only about 0.15. But caffe+ssd can achieve 0.46 (iou:[0.5]).   Thanks.

**Comment by karan6181** [comment]
@qxin can you please share a complete example code where you trained a coco using MXNet SSD. Also, we try to handle questions via the [Discuss Forum](https://discuss.mxnet.io), not via issues.

- Missing Details
- 30+ days old 

@sandeep-krishnamurthy Please apply labels:
- MXNet
- Example

And please close the issue due to inactivity.
@qxin if done in error please feel free to re-open and comment.
Thanks!

**Comment by qxin** [comment]
@sandeep-krishnamurthy Thanks ~ (and sorry, for the inactivity)
