### ISSUE TITLE
NasNet代码问题

### ISSUE THREAD

**Issue by taylover-pei** [apache/incubator-mxnet#9278]
用Gluon编写的NasNet的代码好像问题，运行的时候总提示维度不对。是否能修改以下？

**Comment by karan6181** [comment]
@taylover-pei As per your comments, it seems that you have faced some problem while running NasNet code. Can you please provide more information, such as code examples, library versions, traceback, etc.

Are you referring to this code?
https://github.com/qingzhouzhen/incubator-mxnet/blob/nasnet/python/mxnet/gluon/model_zoo/vision/nasnet.py

Please follow this [template](https://github.com/apache/incubator-mxnet/blob/master/.github/ISSUE_TEMPLATE.md) when you are creating an issue in future this will help the community identify the issue.

- Missing Details
- 30+ days old 

@sandeep-krishnamurthy Please apply labels and also close the issue due to inactivity:
- Gluon
- Example

@taylover-pei  please feel free to re-open and comment if you can reproduce the issue.

Thanks!
