### ISSUE TITLE
I have a problem in the process of cross compiling

### ISSUE THREAD

**Issue by zhangguotai** [apache/incubator-mxnet#9342]
issue:./include/dmlc/./optional.h:67:29: error: 'class dmlc::optional<int>' has no member named 'val'
     std::swap(val, other.val);
I should how to modify?

**Comment by szha** [comment]
Did you update the submodule? `git submodule update --init --recursive`

**Comment by zhangguotai** [comment]
I don‘t your meaning,I have downloaded all files of  github. I want to create dynamic link library int the arm,but having a problem in the process of cross compiling. I should where to execute this order?

**Comment by zhangguotai** [comment]
I don‘t your meaning,I have downloaded all files of github. I want to create dynamic link library int the arm,but having a problem in the process of cross compiling. I should where to execute this order?

At 2018-01-08 12:06:12, "Sheng Zha" <notifications@github.com> wrote:


Did you update the submodule? git submodule update --init --recursive

**Comment by szha** [comment]
Sorry for the confusion. Given the compilation error, the most common cause is that some of the submodules are outdated, which is why I asked whether you updated the submodules. You didn't provide environment information such as that you're doing it on ARM, which is less common, so I didn't think it would be a code problem.

@ZihengJiang would you provide some info on how to compile for ARM?

**Comment by marcoabreu** [comment]
You can also try to use our docker_multiarch containers: https://github.com/apache/incubator-mxnet/tree/master/docker_multiarch

**Comment by karan6181** [comment]
@sandeep-krishnamurthy Can you please add labels:
- ARM
- Pending Requester Info

Also, 30+ day old issue. Please close the issue due to inactivity and no response from the requester.

@zhangguotai Please follow this [template](https://github.com/apache/incubator-mxnet/blob/master/.github/ISSUE_TEMPLATE.md) when you are creating an issue in future since this will help the community to identify the issue faster.
If done in error please feel free to re-open and comment.

Thanks!
