### ISSUE TITLE
The fault in the process of running example

### ISSUE THREAD

**Issue by zhangguotai** [apache/incubator-mxnet#9461]
I had compiled libmxnet.so and  image-classification-predict.When running order that ./image-classification-predict apple.jpg,I got a fault that image-classification-predict: image-classification-predict.cc:238: int main(int, char**): Assertion `pred_hnd' failed.
I looked original code:
MXPredCreate((const char*)json_data.GetBuffer(),
                 (const char*)param_data.GetBuffer(),
                 static_cast<size_t>(param_data.GetLength()),
                 dev_type,
                 dev_id,
                 num_input_nodes,
                 input_keys,
                 input_shape_indptr,
                 input_shape_data,
                 &pred_hnd);
assert(pred_hnd);
I should how to modify my code?????

**Comment by aidan-plenert-macdonald** [comment]
This is really hard to read. Can you clean it up and give more detail?

**Comment by karan6181** [comment]
@zhangguotai Can you please provide more information on the issue. 
Also, Please follow this [template](https://github.com/apache/incubator-mxnet/blob/master/.github/ISSUE_TEMPLATE.md) when you are creating an issue in future since this will help the community to identify the issue faster.

@sandeep-krishnamurthy  Can you please add labels and close the issue due to inactivity:
- C++
- Pending Requester Info

@zhangguotai please feel free to re-open and comment if you can still reproduce the issue.

Thanks!

**Comment by HudsonHuang** [comment]
@zhangguotai Could you tell me how did you solved it? I meet the same problem.
