### ISSUE TITLE
Feature extraction for object detection

### ISSUE THREAD

**Issue by VintonyPadmadiredja** [apache/incubator-mxnet#9610]
Hi,

I was following this tutorial: http://mxnet.incubator.apache.org/tutorials/python/predict_image.html
and was wondering how would I use the extracted features to create a bounding box on the image.

Also the assertion in the code fails when I run the code with a different model
Using resnet-18
> (1, 512)
> Traceback (most recent call last):
>   File "predict.py", line 79, in <module>
>     assert features.shape == (1, 2048)
> AssertionError

features shape is (1,512). Would this affect the feature map?

Thanks.

**Comment by roywei** [comment]
@VintonyPadmadiredja  yes, the feature shape is expected to be different if you use another model.
Please kindly raise your questions via our [Discuss Forums](https://discuss.mxnet.io/). Closing this issue since it's expected. Please reopen if close by mistake and let us know!

@sandeep-krishnamurthy  Please add label Question, and close this issue
Thanks!
