### ISSUE TITLE
undefined symbol: MXSymbolGetNumOutputs

### ISSUE THREAD

**Issue by zhangguotai** [apache/incubator-mxnet#9724]
I had complished testing and training by python file in pc. Now, I am transplanting into arm and executing that import mxnet is ok.
But I encounter this problem- AttributeError: /usr/lib/python2.7/site-packages/mxnet/libmxnet.so: undefined symbol: MXSymbolGetNumOutputs
I don't know how to solve it,

**Comment by reminisce** [comment]
Can you first check whether the file `./src/c_api/c_api_symbolic.cc` exists and the function `MXSymbolGetNumOutputs` is defined in that file and declared in `include/mxnet/c_api.h` when you built the lib?

**Comment by karan6181** [comment]
@sandeep-krishnamurthy Can you please add labels:
- MXNet
- C++
- Pending Requester Info

@zhangguotai could you provide more details on the issue.
Also, please follow this [template](https://github.com/apache/incubator-mxnet/blob/master/.github/ISSUE_TEMPLATE.md) when you are creating an issue in future since this will help the community to identify the issue faster.
Thanks!

**Comment by ddavydenko** [comment]
This seems to me related to C API, not to front end C++ API. @sandeep-krishnamurthy , could you please update labels on this issue: remove "C++" and add "C API".

**Comment by lanking520** [comment]
Hi @zhangguotai are you still facing this issue?

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy @nswamy @anirudh2290 Could you please close the issue due to lack of activity.

@zhangguotai  Please feel free to re-open the issue in case closed in error.

**Comment by kalyc** [comment]
@mxnet-label-bot add [issue-closed]
