### ISSUE TITLE
How to reinitialize the begin_state of an RNN

### ISSUE THREAD

**Issue by ArmageddonKnight** [apache/incubator-mxnet#9811]
I now have an RNN, of which the initial hidden states are initialized to all zeros:

```
    rnn = mx.rnn.SequentialRNNCell()

    
    for i in range(args.num_layers):
        rnn.add(mx.rnn.LSTMCell(num_hidden=args.num_hidden, prefix='lstm_l%d_'%i))

    def sym_gen(seq_len):
        ...
        outputs, _ = rnn.unroll(length=seq_len, inputs=embed, merge_outputs=True)
```
I am hoping to reinitialize the begin state of batch **N + 1** to be the final state of batch **N**. How can I possibly achieve this? Thank you.

**Comment by eric-haibin-lin** [comment]
(If you're using the module API) You can explicitly set the begin state via the `module.set_states` API if you declare begin state variables as one of the state names
https://github.com/apache/incubator-mxnet/blob/master/example/rnn/word_lm/module.py#L54
https://github.com/apache/incubator-mxnet/blob/master/example/rnn/word_lm/module.py#L83-L87

But I'd recommend the Gluon API to do so since it's much more flexible.
https://github.com/apache/incubator-mxnet/tree/master/example/gluon/word_language_model

**Comment by ArmageddonKnight** [comment]
@eric-haibin-lin Thanks. This is what I have been looking for.
